# Summary {#summary}

Well done on making it to the end! Before we sign off, it is a good time to reflect over everything you have achieved over the past few weeks.

## Learning outcomes

Let's review how you have achieved each of the learning outcomes for this section of the module.

1. Produce static and interactive visualisations of spatial data.

In the [first session](#intro), you learned how to load spatial data into R and map the data using a variety of packages. You produced different types of maps, including how to present them effectively or make maps interactive.

2. Identify clustering of point- and area-based data.

Our [second session](#cluster) looked at how we might try to identify spatial clusters for data. First, descriptive techniques were applied on point-based data. Second, using area-based data you calculated spatial weights and looked for clusters using Moran's I approaches.

3. Extend regression-based approaches to incorporate spatial context.

The final learning outcome was achieved through two sessions. First, we extended OLS regression approaches using spatially lagged variables or accounted for the spatial structure of error terms to accommodate [spatial regression techniques](#spatreg). Second, we extended OLS regression approaches to incorporate spatially varying coefficients through [Geographically Weighted Regression](#gwr).

## Further learning

The methods we have covered so far will have given you a good grounding in spatial methods, however they are just a small flavour of the vast range of opportunities thinking spatially can bring to research. Here are a few other areas or methods you can read up on in case you want to take things forward. For each, I have provided a (open access) research example of its application and some example R code/packages for you to see how it can be done.

* **Cartograms** -> *Description:* Maps can lie. They can distort patterns, resulting in the misleading interpretation of data. One distortion comes from the geographical size of zones. Where zones are small they can be hard to see, and hence larger areas may attract your attention. You may have noticed this in the [spatial regression session](#spatreg) when some cities were difficult to see on the maps. Cartograms (including linked methods for distorting area sizes such as hexmaps) offer one way of minimising this bias, through readjusting the geographical sizes of areas based on their underlying population sizes. This can allow for fairer comparisons, especially when mapping *people* rather than *places*. *Research example:* [Worldmapper: The Human Anatomy of a Small Planet](https://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.0040001). *R example:* [Tutorial using ggplot2](https://r-charts.com/spatial/cartogram-ggplot2/).
* **Spatial panel model** -> *Description:* The spatial regression models we have introduced are cross-sectional (i.e., a single point in time) and can not account for the longitudinal nature of datasets (i.e., where we have repeated data points over time for each area). These models can be extended longitudinally, similar to how we might extend the classical regression model to incorporate time, to give stronger tests of associations between predictors and outcomes. *Research example:* [Determining the spatial effects of COVID-19 using the spatial panel data model](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7139267/). *R example:* [Package spml](http://www.jstatsoft.org/v47/i01/).
* **Spatial multi-level** -> *Description:* Multi-level modelling revolutionised health geography, since through nesting individuals within areas you could control for individual level characteristics and, in theory, separate out differences which difference between areas can explain. While these methods are powerful, they do not explicitly account for space since the model does not which areas are located where. There exists spatial extensions to multi-level models. *Research example:* [Methodological paper extending multi-level models to incoporate spatial effects](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0130761). *R example:* [HSAR package](https://cran.r-project.org/web/packages/HSAR/HSAR.pdf).
* **Spatial interaction models and flow data** -> *Description:* Flow data are not frequently found in spatial health research. They refer to where we have observations of spatial interactions between two places. The most common application might be movement data (e.g., in- and out-migration flows between two places). Spatial interaction models extend these data and organise them into a regression framework, that can model the interactions between places to understand what may drive them. *Research example:* [Using a Spatial Interaction Model to Assess the Accessibility of District Parks in Hong Kong](https://www.mdpi.com/2071-1050/9/11/1924). *R example:* [Spatial Interaction Models for Dummies](https://rpubs.com/adam_dennett/257231).
* **Location-allocation** -> *Description:* Where we have spatial points representing sites/locations (e.g., health services), we can try to geographically optimise the locations of sites to improve geographical coverage. This can be useful for locating new site locations, including finding where it is best to place new sites to maximise coverage in areas with low access. *Research example:* [Evaluating the locations of asymptomatic COVID-19 test sites in Liverpool](https://extra.shu.ac.uk/ppp-online/wp-content/uploads/2021/04/thinking-spatially-roll-out-testing-liverpool.pdf). *R example:* [Replicatable code from research example](https://github.com/markagreen/mapping_test_accessibility/blob/main/scripts/location_allocation_model.R).
* **Bayesian extensions** -> *Description:* Bayesian models offer an alternative approach to analysis than frequentist methods. There are a lot of different spatial extensions to Bayesian models, allowing for more flexibility to how we approach our analyses. These approaches are important if we want to utilise generalised linear models. *Research example:* [Evaluating social and spatial inequalities in COVID-19 testing in Liverpool](https://www.sciencedirect.com/science/article/pii/S2666776221000843). *R example:* [Geospatial Health Data Book](https://www.paulamoraga.com/book-geospatial/).
* **Causal inference methods** -> *Description:* There are a large number of techniques that have tried to implement causal inference approaches within a spatial framework. One example of these methods might be spatial regression discontinuity approaches, where you assess impacts of interventions in places through comparisons to the impacts closest to them where they were not implemented. *Research example:* [Review of spatial causal inference methods](https://arxiv.org/abs/2007.02714). *R example:* [SpatialRDD package](https://github.com/axlehner/SpatialRDD).
* **Spatial machine learning** -> *Description:* A relatively newer area of research explores how we can extend machine learning methods to explicitly incorporate space into them. This field is so new that I have very little to report here! *Research example:* [Spatio-temporal predictions using deep learning](https://www.nature.com/articles/s41598-020-79148-7). *R example:* [Statistical Learning tutorial](https://geocompr.robinlovelace.net/spatial-cv.html).

## Thank you

I would just like to end by thanking you for taking the time to read through these materials and hopefully you have enjoyed learning about spatial data analysis. If you have any further questions, please do not hesitate to get in contact.

Dr Mark A. Green \
Senior Lecturer in Health Geography \
University of Liverpool \
<mark.green@liverpool.ac.uk>