--- 
title: "Analysis Methods for Complex Data Structures: Spatial Data"
author: "Mark Green"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
---

# Overview {-}

The resource here is part of the University of Liverpool module:

DASC507 – Advanced Biostatistics II: Analysis Methods for Complex Data Structures

Specifically, the resources contained here are for the 'Spatial Data' part of the module. In the following four sessions we will explain how to deal with spatial data, visualise them, and introduce some techniques for analysising spatial data.

## Learning outcomes {-}

1. Produce static and interactive visualisations of spatial data.
2. Identify clustering of point- and area-based data.
3. Extend regression-based approaches to incorporate spatial context.

## Teaching structure {-}

There are a total of eight sessions as part of the spatial data component of the module. This contains four lectures, which will be short talks introducing concepts and applications within each technique, and four supplementary practicals that will cover how to implement the same techniques within R. The resources here cover the practical sessions, although links to the lecture slides are also provided at the relevant places.

## Computational notebooks {-}

The materials for the practical sessions are embedded within R notebooks. Notebooks are interactive documents that allow for executionable code to be embedded within for running analyses (and presenting their outputs within the same document). They are helpful for teaching, since you can combine analytical code, the resulting output, and interpretation of what was done in a single file. All of the data and scripts are included within the folder structure, meaning that everything should be fully replicatable. Follow the documents along, reading the guidance and testing parts of the code. Feel free to edit the documents and code as you learn, so that you can have one single resource. 

Each package we use in the tutorials will need to be pre-installed. To install any package within R, please use `install.packages("")` and specify the package name in-between `""`. Good R practice is to load all dependencies/packages at the start of any script, however for the purpose of these tutorials we will load each as and when we need them so that you can see when and where they are required.

The course materials are all written using the **bookdown** package [@R-bookdown], which was built on top of R Markdown and **knitr** [@xie2015].

## Contact {-}

Dr Mark A. Green \
Senior Lecturer in Health Geography \
University of Liverpool \
<mark.green@liverpool.ac.uk>


