<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Geographically Weighted Regression | Analysis Methods for Complex Data Structures: Spatial Data</title>
  <meta name="description" content="Chapter 4 Geographically Weighted Regression | Analysis Methods for Complex Data Structures: Spatial Data" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Geographically Weighted Regression | Analysis Methods for Complex Data Structures: Spatial Data" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Geographically Weighted Regression | Analysis Methods for Complex Data Structures: Spatial Data" />
  
  
  

<meta name="author" content="Mark Green" />


<meta name="date" content="2021-09-30" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="spatreg.html"/>
<link rel="next" href="summary.html"/>
<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Spatial Data practical resources for Complex Data Structure</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#learning-outcomes"><i class="fa fa-check"></i>Learning outcomes</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#teaching-structure"><i class="fa fa-check"></i>Teaching structure</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#computational-notebooks"><i class="fa fa-check"></i>Computational notebooks</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#contact"><i class="fa fa-check"></i>Contact</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Mapping data</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#why-map"><i class="fa fa-check"></i><b>1.1</b> Why map?</a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#mapping-in-r"><i class="fa fa-check"></i><b>1.2</b> Mapping in R</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="intro.html"><a href="intro.html#areas"><i class="fa fa-check"></i><b>1.2.1</b> Areas</a></li>
<li class="chapter" data-level="1.2.2" data-path="intro.html"><a href="intro.html#points"><i class="fa fa-check"></i><b>1.2.2</b> Points</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#interactive-maps"><i class="fa fa-check"></i><b>1.3</b> Interactive maps</a></li>
<li class="chapter" data-level="1.4" data-path="intro.html"><a href="intro.html#summary"><i class="fa fa-check"></i><b>1.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="cluster.html"><a href="cluster.html"><i class="fa fa-check"></i><b>2</b> Cluster analysis</a>
<ul>
<li class="chapter" data-level="2.1" data-path="cluster.html"><a href="cluster.html#point-data"><i class="fa fa-check"></i><b>2.1</b> Point data</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="cluster.html"><a href="cluster.html#spatial-histograms"><i class="fa fa-check"></i><b>2.1.1</b> Spatial histograms</a></li>
<li class="chapter" data-level="2.1.2" data-path="cluster.html"><a href="cluster.html#kernal-density-estimation"><i class="fa fa-check"></i><b>2.1.2</b> Kernal Density Estimation</a></li>
<li class="chapter" data-level="2.1.3" data-path="cluster.html"><a href="cluster.html#spatial-interpolation"><i class="fa fa-check"></i><b>2.1.3</b> Spatial interpolation</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="cluster.html"><a href="cluster.html#area-data"><i class="fa fa-check"></i><b>2.2</b> Area data</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="cluster.html"><a href="cluster.html#global-morans-i"><i class="fa fa-check"></i><b>2.2.1</b> Global Moran’s I</a></li>
<li class="chapter" data-level="2.2.2" data-path="cluster.html"><a href="cluster.html#local-morans-i"><i class="fa fa-check"></i><b>2.2.2</b> Local Moran’s I</a></li>
<li class="chapter" data-level="2.2.3" data-path="cluster.html"><a href="cluster.html#getis-ord-gi-statistic"><i class="fa fa-check"></i><b>2.2.3</b> Getis-Ord Gi statistic</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="cluster.html"><a href="cluster.html#summary-1"><i class="fa fa-check"></i><b>2.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="spatreg.html"><a href="spatreg.html"><i class="fa fa-check"></i><b>3</b> Spatial Regression</a>
<ul>
<li class="chapter" data-level="3.1" data-path="spatreg.html"><a href="spatreg.html#exploring-the-data"><i class="fa fa-check"></i><b>3.1</b> Exploring the data</a></li>
<li class="chapter" data-level="3.2" data-path="spatreg.html"><a href="spatreg.html#non-spatial-regression"><i class="fa fa-check"></i><b>3.2</b> Non-spatial regression</a></li>
<li class="chapter" data-level="3.3" data-path="spatreg.html"><a href="spatreg.html#selecting-the-right-spatial-model"><i class="fa fa-check"></i><b>3.3</b> Selecting the right spatial model</a></li>
<li class="chapter" data-level="3.4" data-path="spatreg.html"><a href="spatreg.html#spatial-lag-model"><i class="fa fa-check"></i><b>3.4</b> Spatial lag model</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="spatreg.html"><a href="spatreg.html#slx-spatially-lagged-model"><i class="fa fa-check"></i><b>3.4.1</b> SLX spatially lagged model</a></li>
<li class="chapter" data-level="3.4.2" data-path="spatreg.html"><a href="spatreg.html#sar-spatial-lag"><i class="fa fa-check"></i><b>3.4.2</b> SAR Spatial Lag</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="spatreg.html"><a href="spatreg.html#spatial-error-models"><i class="fa fa-check"></i><b>3.5</b> Spatial error models</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="spatreg.html"><a href="spatreg.html#spatial-error-model-sem"><i class="fa fa-check"></i><b>3.5.1</b> Spatial Error Model (SEM)</a></li>
<li class="chapter" data-level="3.5.2" data-path="spatreg.html"><a href="spatreg.html#spatial-durbin-error"><i class="fa fa-check"></i><b>3.5.2</b> Spatial Durbin Error</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="spatreg.html"><a href="spatreg.html#summary-2"><i class="fa fa-check"></i><b>3.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="gwr.html"><a href="gwr.html"><i class="fa fa-check"></i><b>4</b> Geographically Weighted Regression</a>
<ul>
<li class="chapter" data-level="4.1" data-path="gwr.html"><a href="gwr.html#loading-data"><i class="fa fa-check"></i><b>4.1</b> Loading data</a></li>
<li class="chapter" data-level="4.2" data-path="gwr.html"><a href="gwr.html#selecting-bandwidths"><i class="fa fa-check"></i><b>4.2</b> Selecting bandwidths</a></li>
<li class="chapter" data-level="4.3" data-path="gwr.html"><a href="gwr.html#running-the-model"><i class="fa fa-check"></i><b>4.3</b> Running the model</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="gwr.html"><a href="gwr.html#assessing-model-fit"><i class="fa fa-check"></i><b>4.3.1</b> Assessing model fit</a></li>
<li class="chapter" data-level="4.3.2" data-path="gwr.html"><a href="gwr.html#plotting-coefficients"><i class="fa fa-check"></i><b>4.3.2</b> Plotting coefficients</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="gwr.html"><a href="gwr.html#scaling-gwr-for-large-datasets"><i class="fa fa-check"></i><b>4.4</b> Scaling GWR for large datasets</a></li>
<li class="chapter" data-level="4.5" data-path="gwr.html"><a href="gwr.html#summary-3"><i class="fa fa-check"></i><b>4.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="intro.html"><a href="intro.html#summary"><i class="fa fa-check"></i><b>5</b> Summary</a>
<ul>
<li class="chapter" data-level="5.1" data-path="summary.html"><a href="summary.html"><i class="fa fa-check"></i><b>5.1</b> Learning outcomes</a></li>
<li class="chapter" data-level="5.2" data-path="summary.html"><a href="summary.html#further-learning"><i class="fa fa-check"></i><b>5.2</b> Further learning</a></li>
<li class="chapter" data-level="5.3" data-path="summary.html"><a href="summary.html#thank-you"><i class="fa fa-check"></i><b>5.3</b> Thank you</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Analysis Methods for Complex Data Structures: Spatial Data</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="gwr" class="section level1" number="4">
<h1><span class="header-section-number">Chapter 4</span> Geographically Weighted Regression</h1>
<p>In our last session (boo), we extend the spatial regression approach to explore the concept of spatially varying coefficients. The lecture slides for this practical can be found <a href="">here</a>. A PDF version of the practical can be found <a href="">here</a>.</p>
<div id="loading-data" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Loading data</h2>
<p>We will use the same data introduced in the <a href="%7B#spatreg%7D">previous session</a>. We will this time look at second dose uptake to mix it up. Let’s quickly load in the data and tidy it.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="gwr.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load package</span></span>
<span id="cb1-2"><a href="gwr.html#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span></code></pre></div>
<pre><code>## Registered S3 methods overwritten by &#39;tibble&#39;:
##   method     from  
##   format.tbl pillar
##   print.tbl  pillar</code></pre>
<pre><code>## Linking to GEOS 3.7.2, GDAL 2.4.2, PROJ 5.2.0</code></pre>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="gwr.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load and clean spatial data</span></span>
<span id="cb4-2"><a href="gwr.html#cb4-2" aria-hidden="true" tabindex="-1"></a>lad_uk <span class="ot">&lt;-</span> <span class="fu">read_sf</span>(<span class="st">&quot;./Shapefiles/UK_LAD/Local_Authority_Districts_(December_2019)_Boundaries_UK_BFC.shp&quot;</span>) <span class="co"># Load shapefile for Local Authority Districts (LADs) for UK (sorry but could not find only England version so need to convert to match data)</span></span>
<span id="cb4-3"><a href="gwr.html#cb4-3" aria-hidden="true" tabindex="-1"></a>lad_uk<span class="sc">$</span>country <span class="ot">&lt;-</span> <span class="fu">substr</span>(lad_uk<span class="sc">$</span>lad19cd, <span class="dv">0</span>, <span class="dv">1</span>) <span class="co"># Record first letter of LAD code (denotes country)</span></span>
<span id="cb4-4"><a href="gwr.html#cb4-4" aria-hidden="true" tabindex="-1"></a>lad_eng <span class="ot">&lt;-</span> lad_uk[lad_uk<span class="sc">$</span>country <span class="sc">==</span> <span class="st">&quot;E&quot;</span>,] <span class="co"># Subset only English LADs</span></span>
<span id="cb4-5"><a href="gwr.html#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="gwr.html#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Tidy and join on explanatory variables</span></span>
<span id="cb4-7"><a href="gwr.html#cb4-7" aria-hidden="true" tabindex="-1"></a>lad_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;./Data/LAD_vaccine_data.csv&quot;</span>) <span class="co"># Load vaccine uptake and demographic data for England</span></span>
<span id="cb4-8"><a href="gwr.html#cb4-8" aria-hidden="true" tabindex="-1"></a>lad_eng <span class="ot">&lt;-</span> <span class="fu">merge</span>(lad_eng, lad_data, <span class="at">by.x =</span> <span class="st">&quot;lad19cd&quot;</span>, <span class="at">by.y =</span> <span class="st">&quot;ltla_code&quot;</span>, <span class="at">all.x =</span> <span class="cn">TRUE</span>) <span class="co"># Join on both datasets</span></span>
<span id="cb4-9"><a href="gwr.html#cb4-9" aria-hidden="true" tabindex="-1"></a>lad_eng<span class="sc">$</span>pop_density <span class="ot">&lt;-</span> lad_eng<span class="sc">$</span>population <span class="sc">/</span> (lad_eng<span class="sc">$</span>st_areasha <span class="sc">/</span> <span class="dv">1000000</span>) <span class="co"># Calculate population density (st_areashape is measured in metres^2 so need to convert to km^2 by dividing by 1,000,000)</span></span>
<span id="cb4-10"><a href="gwr.html#cb4-10" aria-hidden="true" tabindex="-1"></a>lad_eng<span class="sc">$</span>percent_first_dose <span class="ot">&lt;-</span> (lad_eng<span class="sc">$</span>total_first_dose <span class="sc">/</span> lad_eng<span class="sc">$</span>population) <span class="sc">*</span> <span class="dv">100</span> <span class="co"># Calculate percent of population who have had their first dose</span></span>
<span id="cb4-11"><a href="gwr.html#cb4-11" aria-hidden="true" tabindex="-1"></a>lad_eng<span class="sc">$</span>percent_second_dose <span class="ot">&lt;-</span> (lad_eng<span class="sc">$</span>total_second_dose <span class="sc">/</span> lad_eng<span class="sc">$</span>population) <span class="sc">*</span> <span class="dv">100</span> <span class="co"># Calculate percent of population who have had their first dose</span></span>
<span id="cb4-12"><a href="gwr.html#cb4-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-13"><a href="gwr.html#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove objects to save space</span></span>
<span id="cb4-14"><a href="gwr.html#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(lad_uk, lad_data) </span></code></pre></div>
<p>Let’s have a look at the spatial pattern of the variable.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="gwr.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load packages</span></span>
<span id="cb5-2"><a href="gwr.html#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2) </span>
<span id="cb5-3"><a href="gwr.html#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(viridis)</span></code></pre></div>
<pre><code>## Loading required package: viridisLite</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="gwr.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb7-2"><a href="gwr.html#cb7-2" aria-hidden="true" tabindex="-1"></a>map1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="co"># Call ggplot command</span></span>
<span id="cb7-3"><a href="gwr.html#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> lad_eng, <span class="fu">aes</span>(<span class="at">fill =</span> percent_second_dose), <span class="at">lwd =</span> <span class="dv">0</span>) <span class="sc">+</span> <span class="co"># Define what to plot</span></span>
<span id="cb7-4"><a href="gwr.html#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis</span>() <span class="sc">+</span> <span class="co"># Make colourblind friendly</span></span>
<span id="cb7-5"><a href="gwr.html#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Longitude&quot;</span>) <span class="sc">+</span> <span class="co"># Add x-axis label</span></span>
<span id="cb7-6"><a href="gwr.html#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Latitude&quot;</span>) <span class="sc">+</span> <span class="co"># Add y-axis label</span></span>
<span id="cb7-7"><a href="gwr.html#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Second dose uptake&quot;</span>, <span class="co"># Edit plot title</span></span>
<span id="cb7-8"><a href="gwr.html#cb7-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">&quot;Percent (%)&quot;</span>) <span class="co"># Edit legend title</span></span>
<span id="cb7-9"><a href="gwr.html#cb7-9" aria-hidden="true" tabindex="-1"></a>map1 <span class="co"># Print plot</span></span></code></pre></div>
<p><img src="Spatial-Data_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>We can see lower uptake in urban areas and higher uptake in rural regions. This is likely reflecting differences in the age-structure of areas.</p>
<p>Let’s use a standard linear regression model to examine the factors that are associated with the percentage of individuals who are fully vaccinated (i.e., received their second vaccine dose). This will be useful to compare to the <strong>Geographically Weighted Regression (GWR)</strong> model later.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="gwr.html#cb8-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(percent_second_dose <span class="sc">~</span> median_age <span class="sc">+</span> Other_White <span class="sc">+</span> Mixed <span class="sc">+</span> Black <span class="sc">+</span> Asian <span class="sc">+</span> Other <span class="sc">+</span> mean_imd_score <span class="sc">+</span> pop_density, <span class="at">data =</span> lad_eng) <span class="co"># OLS model</span></span>
<span id="cb8-2"><a href="gwr.html#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1) <span class="co"># Print model results</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = percent_second_dose ~ median_age + Other_White + 
##     Mixed + Black + Asian + Other + mean_imd_score + pop_density, 
##     data = lad_eng)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -17.9897  -1.5236  -0.1079   1.4989  14.1068 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     4.7972830  2.4171174   1.985 0.048063 *  
## median_age      1.0410090  0.0486634  21.392  &lt; 2e-16 ***
## Other_White    -0.1070692  0.0520983  -2.055 0.040709 *  
## Mixed           0.1228759  0.1817387   0.676 0.499476    
## Black          -0.1811159  0.0587695  -3.082 0.002243 ** 
## Asian          -0.0259803  0.0244621  -1.062 0.289039    
## Other          -0.1225451  0.1258458  -0.974 0.330934    
## mean_imd_score  0.0204583  0.0220153   0.929 0.353474    
## pop_density    -0.0004277  0.0001139  -3.756 0.000206 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.616 on 308 degrees of freedom
## Multiple R-squared:  0.8804, Adjusted R-squared:  0.8773 
## F-statistic: 283.5 on 8 and 308 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The model results suggest the following associations:</p>
<ul>
<li>Median age of a Local Authority is positively associated with the percentage of the population who have had their second vaccine dose, so that older populations had more fully vaccinated individuals</li>
<li>Greater percentages of areas with Black or Other White ethnic groups had lower uptake, with a negative association detected.</li>
<li>Population density was negatively associated to vaccination uptake, with uptake decreasing with increasing population density.</li>
</ul>
</div>
<div id="selecting-bandwidths" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> Selecting bandwidths</h2>
<p>GWR is a technique that allows us to examine how associations between variables may vary across space. It works through selecting a ‘search window’ (here defined as surrounding areas) over each data point (Local Authority District in our example), estimating a regression equation (for the data point and data points in the search window, with closer neighbouring data points given larger weightings), and then repeating the process for all data points. This means the process estimates <em>n</em> regression equations each time (you can probably see here how it can become computationally intensive). The result is a series of regression coefficients for each variable and each area, allowing us to explore how coefficients vary across space.</p>
<p>To be able to estimate a model, we need to define the ‘search window.’ This consists of two components: (i) a spatial kernel, and (ii) bandwidth. The <strong>spatial kernel</strong> refers to the weighting mechanism that gives greater importance/weighting to data points located closer to each data point (and vice versa), and the extent that the weighting changes with distance. The kernel can be fixed (i.e., the same bandwidth, such as a fixed distance, is used for each regression) or adaptive (i.e., varying bandwidths are used, such as nearest number of neighbours). <strong>Bandwidith</strong> is the extent of the kernel (i.e., how big an area it covers).</p>
<p>We can optimise the bandwidth value using a cross-validation. Here we estimate a regression model for a particular location with a set bandwidth value. We then compare the predicted outcome value for the model to the observed/actual value, which gives us the residual error. We can then vary the bandwidth value and see how the residual changes, with the aim of minimising it.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="gwr.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spgwr) <span class="co"># Load package</span></span></code></pre></div>
<pre><code>## Loading required package: sp</code></pre>
<pre><code>## Loading required package: spData</code></pre>
<pre><code>## To access larger datasets in this package, install the spDataLarge
## package with: `install.packages(&#39;spDataLarge&#39;,
## repos=&#39;https://nowosad.github.io/drat/&#39;, type=&#39;source&#39;)`</code></pre>
<pre><code>## NOTE: This package does not constitute approval of GWR
## as a method of spatial analysis; see example(gwr)</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="gwr.html#cb15-1" aria-hidden="true" tabindex="-1"></a>fixed_bandwidth <span class="ot">&lt;-</span> <span class="fu">gwr.sel</span>(percent_second_dose <span class="sc">~</span> median_age <span class="sc">+</span> Other_White <span class="sc">+</span> Mixed <span class="sc">+</span> Black <span class="sc">+</span> Asian <span class="sc">+</span> Other <span class="sc">+</span> mean_imd_score <span class="sc">+</span> pop_density, <span class="at">data =</span> lad_eng, <span class="at">coords =</span> <span class="fu">cbind</span>(lad_eng<span class="sc">$</span>long, lad_eng<span class="sc">$</span>lat), <span class="at">adapt =</span> <span class="cn">FALSE</span>, <span class="at">method =</span> <span class="st">&quot;cv&quot;</span>, <span class="at">longlat =</span> <span class="cn">TRUE</span>) <span class="co"># Select best fixed bandwidth for GWR (can be slow)</span></span></code></pre></div>
<pre><code>## Bandwidth: 307.6284 CV score: 2247.438 
## Bandwidth: 497.2562 CV score: 2262.816 
## Bandwidth: 190.4319 CV score: 2214.023 
## Bandwidth: 118.0005 CV score: 2122.952 
## Bandwidth: 73.23547 CV score: 1992.08 
## Bandwidth: 45.56914 CV score: 1916.536 
## Bandwidth: 28.47041 CV score: 2227.318 
## Bandwidth: 56.13674 CV score: 1935.575 
## Bandwidth: 34.26881 CV score: 1958.648 
## Bandwidth: 47.28953 CV score: 1916.081 
## Bandwidth: 46.99495 CV score: 1916.017 
## Bandwidth: 46.81922 CV score: 1916.005 
## Bandwidth: 46.81148 CV score: 1916.005 
## Bandwidth: 46.81257 CV score: 1916.005 
## Bandwidth: 46.81261 CV score: 1916.005 
## Bandwidth: 46.81253 CV score: 1916.005 
## Bandwidth: 46.81257 CV score: 1916.005</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="gwr.html#cb17-1" aria-hidden="true" tabindex="-1"></a>fixed_bandwidth</span></code></pre></div>
<pre><code>## [1] 46.81257</code></pre>
<p>The output prints details of the model fitting process, but you can switch this off by adding <code>verbose = FALSE</code>. The optimised bandwidth for our model is 46.8125698 kilometers (km). The value suggests that a fixed radius of this distance is set and placed around each data point (area).</p>
<p>Let’s repeat the process, but this time estimate an adaptive bandwidth. This will be useful for comparing model fit later.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="gwr.html#cb19-1" aria-hidden="true" tabindex="-1"></a>adaptive_bandwidth <span class="ot">&lt;-</span> <span class="fu">gwr.sel</span>(percent_second_dose <span class="sc">~</span> median_age <span class="sc">+</span> Other_White <span class="sc">+</span> Mixed <span class="sc">+</span> Black <span class="sc">+</span> Asian <span class="sc">+</span> Other <span class="sc">+</span> mean_imd_score <span class="sc">+</span> pop_density, <span class="at">data =</span> lad_eng, <span class="at">coords =</span> <span class="fu">cbind</span>(lad_eng<span class="sc">$</span>long, lad_eng<span class="sc">$</span>lat), <span class="at">adapt =</span> <span class="cn">TRUE</span>, <span class="at">method =</span> <span class="st">&quot;cv&quot;</span>, <span class="at">longlat =</span> <span class="cn">TRUE</span>, <span class="at">verbose =</span> <span class="cn">TRUE</span>) <span class="co"># Select best adaptive bandwidth for GWR (can be slow)</span></span></code></pre></div>
<pre><code>## Adaptive q: 0.381966 CV score: 2125.007 
## Adaptive q: 0.618034 CV score: 2211.108 
## Adaptive q: 0.236068 CV score: 2016.777 
## Adaptive q: 0.145898 CV score: 1964.669 
## Adaptive q: 0.09016994 CV score: 1900.774 
## Adaptive q: 0.05572809 CV score: 1837.333 
## Adaptive q: 0.03444185 CV score: 1760.934 
## Adaptive q: 0.02128624 CV score: 1691.024 
## Adaptive q: 0.01315562 CV score: 1797.949 
## Adaptive q: 0.02480104 CV score: 1712.084 
## Adaptive q: 0.01818062 CV score: 1718.198 
## Adaptive q: 0.02169819 CV score: 1689.364 
## Adaptive q: 0.02211599 CV score: 1688.373 
## Adaptive q: 0.02314159 CV score: 1696.927 
## Adaptive q: 0.02250172 CV score: 1691.397 
## Adaptive q: 0.0220753 CV score: 1688.142 
## Adaptive q: 0.02196273 CV score: 1688.48 
## Adaptive q: 0.0220323 CV score: 1688.268 
## Adaptive q: 0.0220753 CV score: 1688.142</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="gwr.html#cb21-1" aria-hidden="true" tabindex="-1"></a>adaptive_bandwidth</span></code></pre></div>
<pre><code>## [1] 0.0220753</code></pre>
<p>Here the value of 0.0220753 presents the optimal proportion of neighbours (or k-nearest neighbours) to select as the bandwidth. In this example, we should select 2.2075297% of areas surrounding each data point (or nearest neighbours), or equivalent to selecting <code>nrow(lad_eng) * adaptive_bandwidth</code> areas around each data point each time we run a regression.</p>
</div>
<div id="running-the-model" class="section level2" number="4.3">
<h2><span class="header-section-number">4.3</span> Running the model</h2>
<p>Now that we are ready to fit our GWR model, there are two key areas we need to concentrate on when interpreting any GWR model: (i) model fit, and (ii) the meaning of spatially varying coefficients.</p>
<div id="assessing-model-fit" class="section level3" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> Assessing model fit</h3>
<p>We have so far two types of bandwidth to use in fitting our GWR model. We need to identify which we will use for reporting our results. To make a decision, we will fit two GWR models, one for each of the two bandwidths, and compare their model fits to see which performs better.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="gwr.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model with fixed bandwidth</span></span>
<span id="cb23-2"><a href="gwr.html#cb23-2" aria-hidden="true" tabindex="-1"></a>model2_fixed <span class="ot">&lt;-</span> <span class="fu">gwr</span>(percent_second_dose <span class="sc">~</span> median_age <span class="sc">+</span> Other_White <span class="sc">+</span> Mixed <span class="sc">+</span> Black <span class="sc">+</span> Asian <span class="sc">+</span> Other <span class="sc">+</span> mean_imd_score <span class="sc">+</span> pop_density, <span class="at">data =</span> lad_eng, <span class="at">coords =</span> <span class="fu">cbind</span>(lad_eng<span class="sc">$</span>long, lad_eng<span class="sc">$</span>lat), <span class="at">bandwidth =</span> fixed_bandwidth, <span class="at">hatmatrix =</span> <span class="cn">TRUE</span>, <span class="at">se.fit =</span> <span class="cn">TRUE</span>, <span class="at">longlat =</span> <span class="cn">TRUE</span>) </span>
<span id="cb23-3"><a href="gwr.html#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="gwr.html#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Model with adaptive bandwidth</span></span>
<span id="cb23-5"><a href="gwr.html#cb23-5" aria-hidden="true" tabindex="-1"></a>model2_adapt <span class="ot">&lt;-</span> <span class="fu">gwr</span>(percent_second_dose <span class="sc">~</span> median_age <span class="sc">+</span> Other_White <span class="sc">+</span> Mixed <span class="sc">+</span> Black <span class="sc">+</span> Asian <span class="sc">+</span> Other <span class="sc">+</span> mean_imd_score <span class="sc">+</span> pop_density, <span class="at">data =</span> lad_eng, <span class="at">coords =</span> <span class="fu">cbind</span>(lad_eng<span class="sc">$</span>long, lad_eng<span class="sc">$</span>lat), <span class="at">adapt =</span> adaptive_bandwidth, <span class="at">hatmatrix =</span> <span class="cn">TRUE</span>, <span class="at">se.fit =</span> <span class="cn">TRUE</span>, <span class="at">longlat =</span> <span class="cn">TRUE</span>) <span class="co"># note we use adapt for the bandwidth here</span></span></code></pre></div>
<p>Let’s compare the overall model fit for both of these models. We will just look at the corrected AIC values</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="gwr.html#cb24-1" aria-hidden="true" tabindex="-1"></a>model2_fixed<span class="sc">$</span>results<span class="sc">$</span>AICh <span class="co"># AIC - fixed bandwidth</span></span></code></pre></div>
<pre><code>## [1] 1348.313</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="gwr.html#cb26-1" aria-hidden="true" tabindex="-1"></a>model2_adapt<span class="sc">$</span>results<span class="sc">$</span>AICh <span class="co"># AIC - adaptive bandwidth</span></span></code></pre></div>
<pre><code>## [1] 1246.369</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="gwr.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># model2_fixed$results$AICb # AIC corrected for small sample sizes - fixed bandwidth </span></span>
<span id="cb28-2"><a href="gwr.html#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="co"># model2_adapt$results$AICb # AIC corrected for small sample sizes - adaptive bandwidth</span></span></code></pre></div>
<p>The adaptive bandwidth model has better fit (lower value) and therefore may be preferable on this statistic.</p>
<p>We will next compare the compare the range of local r2 values, to assess model fit performance of our regression models..</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="gwr.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2_fixed<span class="sc">$</span>SDF<span class="sc">$</span>localR2)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.6948  0.9080  0.9268  0.9249  0.9409  0.9999</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="gwr.html#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2_adapt<span class="sc">$</span>SDF<span class="sc">$</span>localR2)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.8521  0.9513  0.9664  0.9607  0.9733  0.9925</code></pre>
<p>Mean and median R2 is higher with the adaptive bandwidth selected, suggesting that on average each areas model fit is better here. If we look at the minimum values, model fit is poorer for the fixed bandwidth as well suggesting the model does less well in particular areas.</p>
<p>Next, we compare the local model fit values to see if one of the models is under/over-performing in particular parts of England. This can give us clues towards whether there are geographical issues in model fit. For example, the use of fixed bandwidths can often lead to too many dissimilar data points selected in regression models (leading to poorer fitting models), or too few data points leading to large uncertainty in estimates. Adaptive bandwidths may vary in their performance spatially given their different sizes of bandwidths.</p>
<p>First, we plot the local R^2 values for the fixed bandwidth model.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="gwr.html#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tidy data</span></span>
<span id="cb33-2"><a href="gwr.html#cb33-2" aria-hidden="true" tabindex="-1"></a>results_fixed <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(model2_fixed<span class="sc">$</span>SDF) <span class="co"># Save coefficients</span></span>
<span id="cb33-3"><a href="gwr.html#cb33-3" aria-hidden="true" tabindex="-1"></a>lad_eng<span class="sc">$</span>fixed_r2 <span class="ot">&lt;-</span> results_fixed<span class="sc">$</span>localR2 <span class="co"># Add local r2 value to data for mapping</span></span>
<span id="cb33-4"><a href="gwr.html#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="gwr.html#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb33-6"><a href="gwr.html#cb33-6" aria-hidden="true" tabindex="-1"></a>map2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="co"># Call ggplot command</span></span>
<span id="cb33-7"><a href="gwr.html#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> lad_eng, <span class="fu">aes</span>(<span class="at">fill =</span> fixed_r2), <span class="at">lwd =</span> <span class="dv">0</span>) <span class="sc">+</span> <span class="co"># Define what to plot</span></span>
<span id="cb33-8"><a href="gwr.html#cb33-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">+</span> <span class="co"># Make colourblind friendly (and set limits to plot for consistency)</span></span>
<span id="cb33-9"><a href="gwr.html#cb33-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Longitude&quot;</span>) <span class="sc">+</span> <span class="co"># Add x-axis label</span></span>
<span id="cb33-10"><a href="gwr.html#cb33-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Latitude&quot;</span>) <span class="sc">+</span> <span class="co"># Add y-axis label</span></span>
<span id="cb33-11"><a href="gwr.html#cb33-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Local model fit (fixed bandwidth)&quot;</span>, <span class="co"># Edit plot title</span></span>
<span id="cb33-12"><a href="gwr.html#cb33-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">&quot;R2 value&quot;</span>) <span class="co"># Edit legend title</span></span>
<span id="cb33-13"><a href="gwr.html#cb33-13" aria-hidden="true" tabindex="-1"></a>map2 <span class="co"># Print plot</span></span></code></pre></div>
<p><img src="Spatial-Data_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>Model fit looks good, but with poorer fit in the North West of England (e.g., Cumbria). Let’s repeat this for the adaptive bandwidth model.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="gwr.html#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tidy data</span></span>
<span id="cb34-2"><a href="gwr.html#cb34-2" aria-hidden="true" tabindex="-1"></a>results_adapt <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(model2_adapt<span class="sc">$</span>SDF) <span class="co"># Save coefficients</span></span>
<span id="cb34-3"><a href="gwr.html#cb34-3" aria-hidden="true" tabindex="-1"></a>lad_eng<span class="sc">$</span>adapt_r2 <span class="ot">&lt;-</span> results_adapt<span class="sc">$</span>localR2 <span class="co"># Add local r2 value to data for mapping</span></span>
<span id="cb34-4"><a href="gwr.html#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="gwr.html#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb34-6"><a href="gwr.html#cb34-6" aria-hidden="true" tabindex="-1"></a>map3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="co"># Call ggplot command</span></span>
<span id="cb34-7"><a href="gwr.html#cb34-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> lad_eng, <span class="fu">aes</span>(<span class="at">fill =</span> adapt_r2), <span class="at">lwd =</span> <span class="dv">0</span>) <span class="sc">+</span> <span class="co"># Define what to plot</span></span>
<span id="cb34-8"><a href="gwr.html#cb34-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">+</span> <span class="co"># Make colourblind friendly (and set limits to plot for consistency)</span></span>
<span id="cb34-9"><a href="gwr.html#cb34-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Longitude&quot;</span>) <span class="sc">+</span> <span class="co"># Add x-axis label</span></span>
<span id="cb34-10"><a href="gwr.html#cb34-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Latitude&quot;</span>) <span class="sc">+</span> <span class="co"># Add y-axis label</span></span>
<span id="cb34-11"><a href="gwr.html#cb34-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Local model fit (adaptive bandwidth)&quot;</span>, <span class="co"># Edit plot title</span></span>
<span id="cb34-12"><a href="gwr.html#cb34-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">&quot;R2 value&quot;</span>) <span class="co"># Edit legend title</span></span>
<span id="cb34-13"><a href="gwr.html#cb34-13" aria-hidden="true" tabindex="-1"></a>map3 <span class="co"># Print plot</span></span></code></pre></div>
<p><img src="Spatial-Data_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>There is some poorer fit in the Northern England and in Cornwall, but otherwise it looks fairly good.</p>
<p>In sum, both of the models are very good. For the purposes of this tutorial, we will use the adaptive bandwidth since it generally has better model fit.</p>
</div>
<div id="plotting-coefficients" class="section level3" number="4.3.2">
<h3><span class="header-section-number">4.3.2</span> Plotting coefficients</h3>
<p>Let’s begin through looking at our overall summary of our analytical model. We can print out the raw output just by running the object in R. I don’t know of a way of cleaning this into a nice and tidy table <del>sorry, not sorry</del>.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="gwr.html#cb35-1" aria-hidden="true" tabindex="-1"></a>model2_fixed</span></code></pre></div>
<pre><code>## Call:
## gwr(formula = percent_second_dose ~ median_age + Other_White + 
##     Mixed + Black + Asian + Other + mean_imd_score + pop_density, 
##     data = lad_eng, coords = cbind(lad_eng$long, lad_eng$lat), 
##     bandwidth = fixed_bandwidth, hatmatrix = TRUE, longlat = TRUE, 
##     se.fit = TRUE)
## Kernel function: gwr.Gauss 
## Fixed bandwidth: 46.81257 
## Summary of GWR coefficient estimates at data points:
##                       Min.     1st Qu.      Median     3rd Qu.        Max.
## X.Intercept.   -2.4903e+01 -9.1887e-01  3.0533e+00  7.3111e+00  1.3355e+02
## median_age     -1.1969e+00  9.7545e-01  1.0405e+00  1.1616e+00  1.6200e+00
## Other_White    -3.3888e-01 -1.7318e-01 -1.6598e-02  7.1306e-02  7.6619e-01
## Mixed          -6.5502e-01  1.0532e-02  3.6080e-01  4.9383e-01  4.1734e+00
## Black          -1.8214e+01 -4.1662e-01 -2.3640e-01 -1.3846e-01 -6.8347e-03
## Asian          -5.2151e+00 -7.6231e-02 -7.4432e-03  5.8227e-03  6.5581e-02
## Other          -9.0439e+00 -1.8882e-01 -1.0064e-01  1.1253e-01  3.0705e+00
## mean_imd_score -7.8441e-01 -5.0281e-02  1.0860e-02  6.3091e-02  2.0162e-01
## pop_density    -7.9592e-04 -7.3941e-04 -5.5343e-05  2.9945e-04  7.5985e-03
##                 Global
## X.Intercept.    4.7973
## median_age      1.0410
## Other_White    -0.1071
## Mixed           0.1229
## Black          -0.1811
## Asian          -0.0260
## Other          -0.1225
## mean_imd_score  0.0205
## pop_density    -0.0004
## Number of data points: 317 
## Effective number of parameters (residual: 2traceS - traceS&#39;S): 94.59721 
## Effective degrees of freedom (residual: 2traceS - traceS&#39;S): 222.4028 
## Sigma (residual: 2traceS - traceS&#39;S): 2.160288 
## Effective number of parameters (model: traceS): 72.72148 
## Effective degrees of freedom (model: traceS): 244.2785 
## Sigma (model: traceS): 2.06129 
## Sigma (ML): 1.809473 
## AICc (GWR p. 61, eq 2.33; p. 96, eq. 4.21): 1468.508 
## AIC (GWR p. 96, eq. 4.22): 1348.313 
## Residual sum of squares: 1037.919 
## Quasi-global R2: 0.9411265</code></pre>
<p>There is a lot of output and information here. Let’s just focus on the summary of the GWR coefficients, which is typically what would be reported in a report. The table presents summary statistics for the coefficients in the model (each coefficient is a row) across all of the local regressions (in our case, all 317 regression models). We may be interested in the minimum and maximum values to see what the range of values are (which is a useful first step to see if coefficients vary in direction). The global model is the same as OLS coefficients and is a useful point of reference to compare to estimates generated in the GWR model. The 1st Quartile, Median and 3rd Quartile values are also useful for considering the variation in values in terms of direction of association and magnitude of strength.</p>
<p>The next step will be to visualise the spatial variations in coefficient values. This will allow us to see if there are any distinct geographical patterns in relationships. We will just plot for the variable IMD score (deprivation). First, let’s plot the coefficient values.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="gwr.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get data</span></span>
<span id="cb37-2"><a href="gwr.html#cb37-2" aria-hidden="true" tabindex="-1"></a>lad_eng<span class="sc">$</span>imd_coef <span class="ot">&lt;-</span> model2_fixed<span class="sc">$</span>SDF<span class="sc">$</span>mean_imd_score <span class="co"># Coefficients</span></span>
<span id="cb37-3"><a href="gwr.html#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="gwr.html#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb37-5"><a href="gwr.html#cb37-5" aria-hidden="true" tabindex="-1"></a>map4 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="co"># Call ggplot command</span></span>
<span id="cb37-6"><a href="gwr.html#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> lad_eng, <span class="fu">aes</span>(<span class="at">fill =</span> imd_coef), <span class="at">lwd =</span> <span class="dv">0</span>) <span class="sc">+</span> <span class="co"># Define what to plot</span></span>
<span id="cb37-7"><a href="gwr.html#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis</span>() <span class="sc">+</span> <span class="co"># Make colourblind friendly</span></span>
<span id="cb37-8"><a href="gwr.html#cb37-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Longitude&quot;</span>) <span class="sc">+</span> <span class="co"># Add x-axis label</span></span>
<span id="cb37-9"><a href="gwr.html#cb37-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Latitude&quot;</span>) <span class="sc">+</span> <span class="co"># Add y-axis label</span></span>
<span id="cb37-10"><a href="gwr.html#cb37-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Deprivation&quot;</span>, <span class="co"># Edit plot title</span></span>
<span id="cb37-11"><a href="gwr.html#cb37-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">&quot;Coefficient&quot;</span>) <span class="co"># Edit legend title</span></span>
<span id="cb37-12"><a href="gwr.html#cb37-12" aria-hidden="true" tabindex="-1"></a>map4 <span class="co"># Print plot</span></span></code></pre></div>
<p><img src="Spatial-Data_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>We may also want to plot the standard errors to look at the variability in the precision of our coefficient estimates.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="gwr.html#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get data</span></span>
<span id="cb38-2"><a href="gwr.html#cb38-2" aria-hidden="true" tabindex="-1"></a>lad_eng<span class="sc">$</span>imd_coef_se <span class="ot">&lt;-</span> model2_fixed<span class="sc">$</span>SDF<span class="sc">$</span>mean_imd_score_se <span class="co"># Standard error</span></span>
<span id="cb38-3"><a href="gwr.html#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="gwr.html#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb38-5"><a href="gwr.html#cb38-5" aria-hidden="true" tabindex="-1"></a>map5 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="co"># Call ggplot command</span></span>
<span id="cb38-6"><a href="gwr.html#cb38-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> lad_eng, <span class="fu">aes</span>(<span class="at">fill =</span> imd_coef_se), <span class="at">lwd =</span> <span class="dv">0</span>) <span class="sc">+</span> <span class="co"># Define what to plot</span></span>
<span id="cb38-7"><a href="gwr.html#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis</span>() <span class="sc">+</span> <span class="co"># Make colourblind friendly</span></span>
<span id="cb38-8"><a href="gwr.html#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Longitude&quot;</span>) <span class="sc">+</span> <span class="co"># Add x-axis label</span></span>
<span id="cb38-9"><a href="gwr.html#cb38-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Latitude&quot;</span>) <span class="sc">+</span> <span class="co"># Add y-axis label</span></span>
<span id="cb38-10"><a href="gwr.html#cb38-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Deprivation&quot;</span>, <span class="co"># Edit plot title</span></span>
<span id="cb38-11"><a href="gwr.html#cb38-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">&quot;Standard Error&quot;</span>) <span class="co"># Edit legend title</span></span>
<span id="cb38-12"><a href="gwr.html#cb38-12" aria-hidden="true" tabindex="-1"></a>map5 <span class="co"># Print plot</span></span></code></pre></div>
<p><img src="Spatial-Data_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>The next step would be to assess the statistical significance of the coefficients to identify if any associations were meaningful. To do this, we estimate the t-value and then categorise observations if they meet 95% level of significance. Let’s plot areas based on whether they meet the criterion.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="gwr.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate t statistic</span></span>
<span id="cb39-2"><a href="gwr.html#cb39-2" aria-hidden="true" tabindex="-1"></a>lad_eng<span class="sc">$</span>t_imd_coef <span class="ot">=</span> results_fixed<span class="sc">$</span>mean_imd_score <span class="sc">/</span> results_fixed<span class="sc">$</span>mean_imd_score_se</span>
<span id="cb39-3"><a href="gwr.html#cb39-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-4"><a href="gwr.html#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Categorise t values as significant or not</span></span>
<span id="cb39-5"><a href="gwr.html#cb39-5" aria-hidden="true" tabindex="-1"></a>lad_eng<span class="sc">$</span>t_imd_coef_cat <span class="ot">&lt;-</span> <span class="fu">cut</span>(lad_eng<span class="sc">$</span>t_imd_coef,</span>
<span id="cb39-6"><a href="gwr.html#cb39-6" aria-hidden="true" tabindex="-1"></a>                     <span class="at">breaks=</span><span class="fu">c</span>(<span class="fu">min</span>(lad_eng<span class="sc">$</span>t_imd_coef), <span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span>, <span class="fu">max</span>(lad_eng<span class="sc">$</span>t_imd_coef)),</span>
<span id="cb39-7"><a href="gwr.html#cb39-7" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;Sig.&quot;</span>,<span class="st">&quot;Non-sig.&quot;</span>, <span class="st">&quot;Sig.&quot;</span>))</span>
<span id="cb39-8"><a href="gwr.html#cb39-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-9"><a href="gwr.html#cb39-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb39-10"><a href="gwr.html#cb39-10" aria-hidden="true" tabindex="-1"></a>map6 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="co"># Call ggplot command</span></span>
<span id="cb39-11"><a href="gwr.html#cb39-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> lad_eng, <span class="fu">aes</span>(<span class="at">fill =</span> t_imd_coef_cat), <span class="at">lwd =</span> <span class="dv">0</span>) <span class="sc">+</span> <span class="co"># Define what to plot</span></span>
<span id="cb39-12"><a href="gwr.html#cb39-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>() <span class="sc">+</span> <span class="co"># Make colourblind friendly</span></span>
<span id="cb39-13"><a href="gwr.html#cb39-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Longitude&quot;</span>) <span class="sc">+</span> <span class="co"># Add x-axis label</span></span>
<span id="cb39-14"><a href="gwr.html#cb39-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Latitude&quot;</span>) <span class="sc">+</span> <span class="co"># Add y-axis label</span></span>
<span id="cb39-15"><a href="gwr.html#cb39-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Deprivation&quot;</span>, <span class="co"># Edit plot title</span></span>
<span id="cb39-16"><a href="gwr.html#cb39-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">&quot;Statistical significance&quot;</span>) <span class="co"># Edit legend title</span></span>
<span id="cb39-17"><a href="gwr.html#cb39-17" aria-hidden="true" tabindex="-1"></a>map6 <span class="co"># Print plot</span></span></code></pre></div>
<p><img src="Spatial-Data_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>It may be useful to combine the coefficient and statistical significance plots into one single visualisation. You could do this by joining the two plots together side-by-side using a R package like <code>patchwork</code>. Rather, we will only plot significant associations and hide those which are not.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="gwr.html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb40-2"><a href="gwr.html#cb40-2" aria-hidden="true" tabindex="-1"></a>map7 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="co"># Call ggplot command</span></span>
<span id="cb40-3"><a href="gwr.html#cb40-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>(<span class="at">data =</span> lad_eng, <span class="at">lwd =</span> <span class="dv">0</span>) <span class="sc">+</span> <span class="co"># Plot all areas as base layer</span></span>
<span id="cb40-4"><a href="gwr.html#cb40-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>(<span class="at">data =</span> lad_eng[lad_eng<span class="sc">$</span>t_imd_coef_cat <span class="sc">==</span> <span class="st">&quot;Sig.&quot;</span>,], <span class="fu">aes</span>(<span class="at">fill =</span> imd_coef), <span class="at">lwd =</span> <span class="dv">0</span>) <span class="sc">+</span> <span class="co"># Plot the coefficients that are significant</span></span>
<span id="cb40-5"><a href="gwr.html#cb40-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_viridis</span>() <span class="sc">+</span> <span class="co"># Make colourblind friendly</span></span>
<span id="cb40-6"><a href="gwr.html#cb40-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">&quot;Longitude&quot;</span>) <span class="sc">+</span> <span class="co"># Add x-axis label</span></span>
<span id="cb40-7"><a href="gwr.html#cb40-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">&quot;Latitude&quot;</span>) <span class="sc">+</span> <span class="co"># Add y-axis label</span></span>
<span id="cb40-8"><a href="gwr.html#cb40-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Deprivation&quot;</span>, <span class="co"># Edit plot title</span></span>
<span id="cb40-9"><a href="gwr.html#cb40-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">fill =</span> <span class="st">&quot;Coefficient&quot;</span>) <span class="co"># Edit legend title</span></span>
<span id="cb40-10"><a href="gwr.html#cb40-10" aria-hidden="true" tabindex="-1"></a>map7 <span class="co"># Print plot</span></span></code></pre></div>
<p><img src="Spatial-Data_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Why not have a look at other coefficients now - what can you find out? What interesting spatial patterns are there?</p>
</div>
</div>
<div id="scaling-gwr-for-large-datasets" class="section level2" number="4.4">
<h2><span class="header-section-number">4.4</span> Scaling GWR for large datasets</h2>
<p>GWR models are computationally intensive to fit and therefore do not scale well with larger datasets (even those with 10000+ observations can be demanding). Some clever cookies have adapted the methodology to estimate the model quicker when dealing with larger or more complex datasets, including creating the R package <code>scgwr</code> (SCalable GWR) to implement the method in R. You can read more about the methodology <a href="https://www.tandfonline.com/doi/full/10.1080/24694452.2020.1774350">here</a>.</p>
<p>The actual code is not too difficult to use, but may require some refinement to model parameters. Specifically, we may want to play about with:</p>
<ul>
<li><code>knn</code> - Number of nearest-neighbours selected during estimation: larger is better for bigger datasets.</li>
<li><code>nsamp</code> - Number of random samples for (aproximate) cross-validation: should be smaller than sample size, but larger is better for minimising errors due to random sampling.</li>
</ul>
<p>Let’s re-run the model again, but using the <code>scgwr</code> package. Unfortunately, this code does not work with our example so I leave it in here to show the option for you in case you ever need it. If you can fix it, please send in your answers on a postcode.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="gwr.html#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># # Library</span></span>
<span id="cb41-2"><a href="gwr.html#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="co"># library(scgwr)</span></span>
<span id="cb41-3"><a href="gwr.html#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb41-4"><a href="gwr.html#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="co"># # Tidy data</span></span>
<span id="cb41-5"><a href="gwr.html#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="co"># outcome &lt;- lad_eng[, &quot;percent_second_dose&quot;] # Store outcome variable (if don&#39;t define as object then stores as list)</span></span>
<span id="cb41-6"><a href="gwr.html#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="co"># xvars &lt;- lad_eng[, c(&quot;median_age&quot;, &quot;Other_White&quot;, &quot;Mixed&quot;, &quot;Black&quot;, &quot;Asian&quot;, &quot;Other&quot;, &quot;mean_imd_score&quot;, &quot;pop_density&quot;)] # Store explanatory variables</span></span>
<span id="cb41-7"><a href="gwr.html#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="co"># xy &lt;- lad_eng[, c(&quot;long&quot;, &quot;lat&quot;)] # Store co-ordinates</span></span>
<span id="cb41-8"><a href="gwr.html#cb41-8" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb41-9"><a href="gwr.html#cb41-9" aria-hidden="true" tabindex="-1"></a><span class="co"># # Model</span></span>
<span id="cb41-10"><a href="gwr.html#cb41-10" aria-hidden="true" tabindex="-1"></a><span class="co"># model3 &lt;- scgwr(y = outcome, x = xvars, coords = xy, knn = 100, kernel = &quot;gau&quot;, p = 4, approach = &quot;CV&quot;) # Model using cross-validation approach (&quot;CV&quot;) and Gaussian kernel (&quot;gau&quot;)</span></span></code></pre></div>
<p>The R package can incorporate parallel processing for faster processing as well using the <code>scgwr_p</code> command.</p>
</div>
<div id="summary-3" class="section level2" number="4.5">
<h2><span class="header-section-number">4.5</span> Summary</h2>
<p>In this practical session, we have explored how use Geographically Weighted Regression and explored the opportunities that it can bring for exploring spatially varying contexts.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="spatreg.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="summary.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Spatial Data.pdf", "Spatial Data.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
