<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Spatial Regression | Analysis Methods for Complex Data Structures: Spatial Data</title>
  <meta name="description" content="Chapter 3 Spatial Regression | Analysis Methods for Complex Data Structures: Spatial Data" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Spatial Regression | Analysis Methods for Complex Data Structures: Spatial Data" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Spatial Regression | Analysis Methods for Complex Data Structures: Spatial Data" />
  
  
  

<meta name="author" content="Mark Green" />


<meta name="date" content="2021-10-15" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="cluster.html"/>
<link rel="next" href="gwr.html"/>
<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/Proj4Leaflet-1.0.1/proj4-compressed.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.0.3/leaflet.js"></script>
<script src="libs/leaflet-providers-1.9.0/leaflet-providers_1.9.0.js"></script>
<script src="libs/leaflet-providers-plugin-2.0.3/leaflet-providers-plugin.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Spatial Data practical resources for Complex Data Structure</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#learning-outcomes"><i class="fa fa-check"></i>Learning outcomes</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#teaching-structure"><i class="fa fa-check"></i>Teaching structure</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#computational-notebooks"><i class="fa fa-check"></i>Computational notebooks</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#contact"><i class="fa fa-check"></i>Contact</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="whymap.html"><a href="whymap.html"><i class="fa fa-check"></i><b>1</b> Mapping data</a>
<ul>
<li class="chapter" data-level="1.1" data-path="whymap.html"><a href="whymap.html#why-map"><i class="fa fa-check"></i><b>1.1</b> Why map?</a></li>
<li class="chapter" data-level="1.2" data-path="whymap.html"><a href="whymap.html#mapping-in-r"><i class="fa fa-check"></i><b>1.2</b> Mapping in R</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="whymap.html"><a href="whymap.html#areas"><i class="fa fa-check"></i><b>1.2.1</b> Areas</a></li>
<li class="chapter" data-level="1.2.2" data-path="whymap.html"><a href="whymap.html#points"><i class="fa fa-check"></i><b>1.2.2</b> Points</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="whymap.html"><a href="whymap.html#interactive-maps"><i class="fa fa-check"></i><b>1.3</b> Interactive maps</a></li>
<li class="chapter" data-level="1.4" data-path="whymap.html"><a href="whymap.html#summary"><i class="fa fa-check"></i><b>1.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="cluster.html"><a href="cluster.html"><i class="fa fa-check"></i><b>2</b> Cluster analysis</a>
<ul>
<li class="chapter" data-level="2.1" data-path="cluster.html"><a href="cluster.html#point-data"><i class="fa fa-check"></i><b>2.1</b> Point data</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="cluster.html"><a href="cluster.html#spatial-histograms"><i class="fa fa-check"></i><b>2.1.1</b> Spatial histograms</a></li>
<li class="chapter" data-level="2.1.2" data-path="cluster.html"><a href="cluster.html#kernal-density-estimation"><i class="fa fa-check"></i><b>2.1.2</b> Kernal Density Estimation</a></li>
<li class="chapter" data-level="2.1.3" data-path="cluster.html"><a href="cluster.html#spatial-interpolation"><i class="fa fa-check"></i><b>2.1.3</b> Spatial interpolation</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="cluster.html"><a href="cluster.html#area-data"><i class="fa fa-check"></i><b>2.2</b> Area data</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="cluster.html"><a href="cluster.html#global-morans-i"><i class="fa fa-check"></i><b>2.2.1</b> Global Moran’s I</a></li>
<li class="chapter" data-level="2.2.2" data-path="cluster.html"><a href="cluster.html#local-morans-i"><i class="fa fa-check"></i><b>2.2.2</b> Local Moran’s I</a></li>
<li class="chapter" data-level="2.2.3" data-path="cluster.html"><a href="cluster.html#getis-ord-gi-statistic"><i class="fa fa-check"></i><b>2.2.3</b> Getis-Ord Gi statistic</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="cluster.html"><a href="cluster.html#summary-1"><i class="fa fa-check"></i><b>2.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="spatreg.html"><a href="spatreg.html"><i class="fa fa-check"></i><b>3</b> Spatial Regression</a>
<ul>
<li class="chapter" data-level="3.1" data-path="spatreg.html"><a href="spatreg.html#exploring-the-data"><i class="fa fa-check"></i><b>3.1</b> Exploring the data</a></li>
<li class="chapter" data-level="3.2" data-path="spatreg.html"><a href="spatreg.html#non-spatial-regression"><i class="fa fa-check"></i><b>3.2</b> Non-spatial regression</a></li>
<li class="chapter" data-level="3.3" data-path="spatreg.html"><a href="spatreg.html#selecting-the-right-spatial-model"><i class="fa fa-check"></i><b>3.3</b> Selecting the right spatial model</a></li>
<li class="chapter" data-level="3.4" data-path="spatreg.html"><a href="spatreg.html#spatial-lag-model"><i class="fa fa-check"></i><b>3.4</b> Spatial lag model</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="spatreg.html"><a href="spatreg.html#slx-spatially-lagged-model"><i class="fa fa-check"></i><b>3.4.1</b> SLX spatially lagged model</a></li>
<li class="chapter" data-level="3.4.2" data-path="spatreg.html"><a href="spatreg.html#sar-spatial-lag"><i class="fa fa-check"></i><b>3.4.2</b> SAR Spatial Lag</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="spatreg.html"><a href="spatreg.html#spatial-error-models"><i class="fa fa-check"></i><b>3.5</b> Spatial error models</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="spatreg.html"><a href="spatreg.html#spatial-error-model-sem"><i class="fa fa-check"></i><b>3.5.1</b> Spatial Error Model (SEM)</a></li>
<li class="chapter" data-level="3.5.2" data-path="spatreg.html"><a href="spatreg.html#spatial-durbin-error"><i class="fa fa-check"></i><b>3.5.2</b> Spatial Durbin Error</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="spatreg.html"><a href="spatreg.html#summary-2"><i class="fa fa-check"></i><b>3.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="gwr.html"><a href="gwr.html"><i class="fa fa-check"></i><b>4</b> Geographically Weighted Regression</a>
<ul>
<li class="chapter" data-level="4.1" data-path="gwr.html"><a href="gwr.html#loading-data"><i class="fa fa-check"></i><b>4.1</b> Loading data</a></li>
<li class="chapter" data-level="4.2" data-path="gwr.html"><a href="gwr.html#selecting-bandwidths"><i class="fa fa-check"></i><b>4.2</b> Selecting bandwidths</a></li>
<li class="chapter" data-level="4.3" data-path="gwr.html"><a href="gwr.html#running-the-model"><i class="fa fa-check"></i><b>4.3</b> Running the model</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="gwr.html"><a href="gwr.html#assessing-model-fit"><i class="fa fa-check"></i><b>4.3.1</b> Assessing model fit</a></li>
<li class="chapter" data-level="4.3.2" data-path="gwr.html"><a href="gwr.html#plotting-coefficients"><i class="fa fa-check"></i><b>4.3.2</b> Plotting coefficients</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="gwr.html"><a href="gwr.html#scaling-gwr-for-large-datasets"><i class="fa fa-check"></i><b>4.4</b> Scaling GWR for large datasets</a></li>
<li class="chapter" data-level="4.5" data-path="gwr.html"><a href="gwr.html#summary-3"><i class="fa fa-check"></i><b>4.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="whymap.html"><a href="whymap.html#summary"><i class="fa fa-check"></i><b>5</b> Summary</a>
<ul>
<li class="chapter" data-level="5.1" data-path="summary.html"><a href="summary.html"><i class="fa fa-check"></i><b>5.1</b> Learning outcomes</a></li>
<li class="chapter" data-level="5.2" data-path="summary.html"><a href="summary.html#further-learning"><i class="fa fa-check"></i><b>5.2</b> Further learning</a></li>
<li class="chapter" data-level="5.3" data-path="summary.html"><a href="summary.html#thank-you"><i class="fa fa-check"></i><b>5.3</b> Thank you</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Analysis Methods for Complex Data Structures: Spatial Data</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="spatreg" class="section level1" number="3">
<h1><span class="header-section-number">Chapter 3</span> Spatial Regression</h1>
<p>So far we have learned how to visualise spatial data and explore if patterns display clustering of high/low values. However, what if we want to understand the predictors of spatial patterns? In this section, we extend regression techniques to incorporate the spatial structure of data. The lecture slides for this practical can be found here: <a href="https://github.com/markagreen/spatial_data/blob/main/Lectures/Spatial%20Regression.pptx">powerpoint</a> or <a href="https://github.com/markagreen/spatial_data/blob/main/Lectures/Spatial%20Regression.pdf">pdf</a>.</p>
<div id="exploring-the-data" class="section level2" number="3.1">
<h2><span class="header-section-number">3.1</span> Exploring the data</h2>
<p>In this tutorial, we will focus on understanding geographical patterns in COVID-19 vaccination uptake. Our analysis will use data collected for Local Authorities Districts (LADs). LADs are large administrative areas that correspond to Local Government areas, typically equivalent to a city, large town or region.</p>
<p>I have collected data on uptake of COVID-19 vaccines (split by number of first and second doses upto 17th June 2021 from <a href="https://www.england.nhs.uk/statistics/statistical-work-areas/covid-19-vaccinations/">here</a>. We will focus on the percentage of people who have had their first vaccination dose as our outcome variable of interest here. I have also compiled a suite of explanatory and contextual variables to help understand patterns in vaccination uptake. These include:</p>
<ul>
<li><strong>Population</strong> data was gathered to provde the denominator for our outcome variables. These data are for mid-year 2019 (~July) and were the most recent available statistics available at the time. Data were downloaded from <a href="https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/datasets/populationestimatesforukenglandandwalesscotlandandnorthernireland">here</a>.</li>
<li><strong>Population density</strong> is also calculated using the population estimates based on the ratio of people to the size of the area. We use this variable to account for urban and rural differences in population (as a proxy).</li>
<li><strong>Median age</strong> was collected from the above population data, to account for the local age structure of areas since older groups could receive their vaccine at an earlier date.</li>
<li><strong>Ethnicity</strong> is measured in aggregated ethnic groups. This was selected because of evidence that some ethnic groups have been targeted with misinformation that may have put them off getting their vaccine. We use estimate population counts for 2019 from <a href="https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/datasets/populationcharacteristicsresearchtables">here</a>. I cleaned the data and converted the population estimates into percentages for the purpose of our analyses. The following aggregated ethnic groups are available: White British, Other White, Black or Black British, Asian or Asian British, Other Ethnicity. For analyses, we will look at all groups other than White British as we hypothesise they may have the highest uptake rates.</li>
<li><strong>Deprivation</strong> was measured using the Index of Multiple Deprivation score (2019). The composite index is the most commonly used measure of deprivation used by researchers and policy officials. We include deprivation in our analyses as we hypothesise that uptake will be lower in more deprived areas. The data are openly available <a href="https://www.gov.uk/government/statistics/english-indices-of-deprivation-2019">here</a>.</li>
</ul>
<p>Let’s load the data into R and tidy it up.</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="spatreg.html#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load package</span></span>
<span id="cb65-2"><a href="spatreg.html#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb65-3"><a href="spatreg.html#cb65-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-4"><a href="spatreg.html#cb65-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load and clean spatial data</span></span>
<span id="cb65-5"><a href="spatreg.html#cb65-5" aria-hidden="true" tabindex="-1"></a>lad_uk <span class="ot">&lt;-</span> <span class="fu">read_sf</span>(<span class="st">&quot;./Shapefiles/UK_LAD/Local_Authority_Districts_(December_2019)_Boundaries_UK_BFC.shp&quot;</span>) <span class="co"># Load shapefile for Local Authority Districts (LADs) for UK (sorry but could not find only England version so need to convert to match data)</span></span>
<span id="cb65-6"><a href="spatreg.html#cb65-6" aria-hidden="true" tabindex="-1"></a>lad_uk<span class="sc">$</span>country <span class="ot">&lt;-</span> <span class="fu">substr</span>(lad_uk<span class="sc">$</span>lad19cd, <span class="dv">0</span>, <span class="dv">1</span>) <span class="co"># Record first letter of LAD code (denotes country)</span></span>
<span id="cb65-7"><a href="spatreg.html#cb65-7" aria-hidden="true" tabindex="-1"></a>lad_eng <span class="ot">&lt;-</span> lad_uk[lad_uk<span class="sc">$</span>country <span class="sc">==</span> <span class="st">&quot;E&quot;</span>,] <span class="co"># Subset only English LADs</span></span>
<span id="cb65-8"><a href="spatreg.html#cb65-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-9"><a href="spatreg.html#cb65-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Tidy and join on explanatory variables</span></span>
<span id="cb65-10"><a href="spatreg.html#cb65-10" aria-hidden="true" tabindex="-1"></a>lad_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;./Data/LAD_vaccine_data.csv&quot;</span>) <span class="co"># Load vaccine uptake and demographic data for England</span></span>
<span id="cb65-11"><a href="spatreg.html#cb65-11" aria-hidden="true" tabindex="-1"></a>lad_eng <span class="ot">&lt;-</span> <span class="fu">merge</span>(lad_eng, lad_data, <span class="at">by.x =</span> <span class="st">&quot;lad19cd&quot;</span>, <span class="at">by.y =</span> <span class="st">&quot;ltla_code&quot;</span>, <span class="at">all.x =</span> <span class="cn">TRUE</span>) <span class="co"># Join on both datasets</span></span>
<span id="cb65-12"><a href="spatreg.html#cb65-12" aria-hidden="true" tabindex="-1"></a>lad_eng<span class="sc">$</span>pop_density <span class="ot">&lt;-</span> lad_eng<span class="sc">$</span>population <span class="sc">/</span> (lad_eng<span class="sc">$</span>st_areasha <span class="sc">/</span> <span class="dv">1000000</span>) <span class="co"># Calculate population density (st_areashape is measured in metres^2 so need to convert to km^2 by dividing by 1,000,000)</span></span>
<span id="cb65-13"><a href="spatreg.html#cb65-13" aria-hidden="true" tabindex="-1"></a>lad_eng<span class="sc">$</span>percent_first_dose <span class="ot">&lt;-</span> (lad_eng<span class="sc">$</span>total_first_dose <span class="sc">/</span> lad_eng<span class="sc">$</span>population) <span class="sc">*</span> <span class="dv">100</span> <span class="co"># Calculate outcome variable</span></span>
<span id="cb65-14"><a href="spatreg.html#cb65-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-15"><a href="spatreg.html#cb65-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove objects to save space</span></span>
<span id="cb65-16"><a href="spatreg.html#cb65-16" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(lad_uk, lad_data) </span></code></pre></div>
<p>The first step is to visualise our outcome variable and examine if there are any spatial patterns. Ideally we would age-standardise our outcome since older age groups were allowed to be vaccinated at early dates, but for simplicity we will stick with the raw percentage of uptake <del>don’t have a go at my laziness</del>.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="spatreg.html#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load packages</span></span>
<span id="cb66-2"><a href="spatreg.html#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2) </span>
<span id="cb66-3"><a href="spatreg.html#cb66-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(viridis)</span>
<span id="cb66-4"><a href="spatreg.html#cb66-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-5"><a href="spatreg.html#cb66-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb66-6"><a href="spatreg.html#cb66-6" aria-hidden="true" tabindex="-1"></a>map1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="co"># Call ggplot command</span></span>
<span id="cb66-7"><a href="spatreg.html#cb66-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> lad_eng, <span class="fu">aes</span>(<span class="at">fill =</span> percent_first_dose), <span class="at">lwd =</span> <span class="dv">0</span>) <span class="sc">+</span> <span class="co"># Define what to plot</span></span>
<span id="cb66-8"><a href="spatreg.html#cb66-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis</span>() <span class="sc">+</span> <span class="co"># Make colourblind friendly</span></span>
<span id="cb66-9"><a href="spatreg.html#cb66-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Longitude&quot;</span>) <span class="sc">+</span> <span class="co"># Add x-axis label</span></span>
<span id="cb66-10"><a href="spatreg.html#cb66-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Latitude&quot;</span>) <span class="sc">+</span> <span class="co"># Add y-axis label</span></span>
<span id="cb66-11"><a href="spatreg.html#cb66-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;First dose uptake&quot;</span>, <span class="co"># Edit plot title</span></span>
<span id="cb66-12"><a href="spatreg.html#cb66-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">&quot;Percent (%)&quot;</span>) <span class="co"># Edit legend title</span></span>
<span id="cb66-13"><a href="spatreg.html#cb66-13" aria-hidden="true" tabindex="-1"></a>map1 <span class="co"># Print plot</span></span></code></pre></div>
<p><img src="Spatial-Data_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
<p>What are the main spatial patterns that you can observe? There is lower uptake in urban areas, especially London, although many of these areas are small on the map due taking up smaller land mass. Else, there is probably not any other distinct spatial pattern.</p>
</div>
<div id="non-spatial-regression" class="section level2" number="3.2">
<h2><span class="header-section-number">3.2</span> Non-spatial regression</h2>
<p>If we wanted to understand why uptake was higher or lower in certain areas, we might use a regression model. If we focus on the standard OLS regression model, we utilise the following equation:</p>
<p><span class="math display">\[
y = X\beta + \epsilon
\]</span></p>
<p>Here, we predict <span class="math inline">\(y\)</span> as a function of a series of predictor <span class="math inline">\(X\)</span> variables that we adjust their effects based on <span class="math inline">\(\beta\)</span> values and some measure of the error <span class="math inline">\(\epsilon\)</span>. We can use an OLS regression model to help us explain patterns in uptake, based on our explanatory variables.</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="spatreg.html#cb67-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(percent_first_dose <span class="sc">~</span> median_age <span class="sc">+</span> Other_White <span class="sc">+</span> Mixed <span class="sc">+</span> Black <span class="sc">+</span> Asian <span class="sc">+</span> Other <span class="sc">+</span> mean_imd_score <span class="sc">+</span> pop_density, <span class="at">data =</span> lad_eng) <span class="co"># Fit a linear regression model for the following equation (outcome ~ explanatory)</span></span>
<span id="cb67-2"><a href="spatreg.html#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1) <span class="co"># Print model results summary</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = percent_first_dose ~ median_age + Other_White + 
##     Mixed + Black + Asian + Other + mean_imd_score + pop_density, 
##     data = lad_eng)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -11.0686  -1.3129  -0.1212   1.2518   7.0054 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     3.203e+01  2.113e+00  15.155  &lt; 2e-16 ***
## median_age      8.150e-01  4.255e-02  19.155  &lt; 2e-16 ***
## Other_White    -7.320e-02  4.555e-02  -1.607   0.1091    
## Mixed           4.014e-01  1.589e-01   2.526   0.0120 *  
## Black          -2.516e-01  5.138e-02  -4.896 1.58e-06 ***
## Asian           1.910e-02  2.139e-02   0.893   0.3724    
## Other          -1.406e-01  1.100e-01  -1.278   0.2021    
## mean_imd_score -9.943e-02  1.925e-02  -5.166 4.31e-07 ***
## pop_density    -2.440e-04  9.955e-05  -2.451   0.0148 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.287 on 308 degrees of freedom
## Multiple R-squared:  0.8612, Adjusted R-squared:  0.8576 
## F-statistic: 238.9 on 8 and 308 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Urgh, what ugly output. I mean it is functional, but not pretty. Good thing we can make the output nicer using various packages in R. I really like <code>gtsummary</code> which can clean regression tables up.</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="spatreg.html#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gtsummary) <span class="co"># Load package</span></span>
<span id="cb69-2"><a href="spatreg.html#cb69-2" aria-hidden="true" tabindex="-1"></a>tbl_model1 <span class="ot">&lt;-</span> <span class="fu">tbl_regression</span>(model1, <span class="at">label =</span> <span class="fu">list</span>(median_age <span class="sc">~</span> <span class="st">&quot;Median age&quot;</span>, Other_White <span class="sc">~</span> <span class="st">&quot;Other White (%)&quot;</span>, Mixed <span class="sc">~</span> <span class="st">&quot;Mixed (%)&quot;</span>, Black <span class="sc">~</span> <span class="st">&quot;Black (%)&quot;</span>, Asian <span class="sc">~</span> <span class="st">&quot;Asian (%)&quot;</span>, Other <span class="sc">~</span> <span class="st">&quot;Other Ethnicity (%)&quot;</span>, mean_imd_score <span class="sc">~</span> <span class="st">&quot;Deprivation score&quot;</span>, pop_density <span class="sc">~</span> <span class="st">&quot;Population density&quot;</span>)) <span class="co"># Make tidy table</span></span>
<span id="cb69-3"><a href="spatreg.html#cb69-3" aria-hidden="true" tabindex="-1"></a>tbl_model1 <span class="co"># Print</span></span></code></pre></div>
<div id="gsmlykpuhb" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#gsmlykpuhb .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#gsmlykpuhb .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#gsmlykpuhb .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#gsmlykpuhb .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#gsmlykpuhb .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#gsmlykpuhb .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#gsmlykpuhb .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#gsmlykpuhb .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#gsmlykpuhb .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#gsmlykpuhb .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#gsmlykpuhb .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#gsmlykpuhb .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#gsmlykpuhb .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#gsmlykpuhb .gt_from_md > :first-child {
  margin-top: 0;
}

#gsmlykpuhb .gt_from_md > :last-child {
  margin-bottom: 0;
}

#gsmlykpuhb .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#gsmlykpuhb .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#gsmlykpuhb .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#gsmlykpuhb .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#gsmlykpuhb .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#gsmlykpuhb .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#gsmlykpuhb .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#gsmlykpuhb .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#gsmlykpuhb .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#gsmlykpuhb .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#gsmlykpuhb .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#gsmlykpuhb .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#gsmlykpuhb .gt_left {
  text-align: left;
}

#gsmlykpuhb .gt_center {
  text-align: center;
}

#gsmlykpuhb .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#gsmlykpuhb .gt_font_normal {
  font-weight: normal;
}

#gsmlykpuhb .gt_font_bold {
  font-weight: bold;
}

#gsmlykpuhb .gt_font_italic {
  font-style: italic;
}

#gsmlykpuhb .gt_super {
  font-size: 65%;
}

#gsmlykpuhb .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 65%;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Beta</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>95% CI</strong><sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>p-value</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">Median age</td>
<td class="gt_row gt_center">0.81</td>
<td class="gt_row gt_center">0.73, 0.90</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">Other White (%)</td>
<td class="gt_row gt_center">-0.07</td>
<td class="gt_row gt_center">-0.16, 0.02</td>
<td class="gt_row gt_center">0.11</td></tr>
    <tr><td class="gt_row gt_left">Mixed (%)</td>
<td class="gt_row gt_center">0.40</td>
<td class="gt_row gt_center">0.09, 0.71</td>
<td class="gt_row gt_center">0.012</td></tr>
    <tr><td class="gt_row gt_left">Black (%)</td>
<td class="gt_row gt_center">-0.25</td>
<td class="gt_row gt_center">-0.35, -0.15</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">Asian (%)</td>
<td class="gt_row gt_center">0.02</td>
<td class="gt_row gt_center">-0.02, 0.06</td>
<td class="gt_row gt_center">0.4</td></tr>
    <tr><td class="gt_row gt_left">Other Ethnicity (%)</td>
<td class="gt_row gt_center">-0.14</td>
<td class="gt_row gt_center">-0.36, 0.08</td>
<td class="gt_row gt_center">0.2</td></tr>
    <tr><td class="gt_row gt_left">Deprivation score</td>
<td class="gt_row gt_center">-0.10</td>
<td class="gt_row gt_center">-0.14, -0.06</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">Population density</td>
<td class="gt_row gt_center">0.00</td>
<td class="gt_row gt_center">0.00, 0.00</td>
<td class="gt_row gt_center">0.015</td></tr>
  </tbody>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="4">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>1</em>
          </sup>
           
          CI = Confidence Interval
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table>
</div>
<p>What does the model say?</p>
<ul>
<li>Median age was positively associated with the percentage of the population who were vaccinated, with areas that had older populations on average being associated with higher uptake.</li>
<li>There are mixed associations found for the ethnicity variables - a negative association between the percentage of an area’s population that were Black or Black British and uptake (i.e., uptake was lower in areas with a higher share of the population that were Black), a positive association between Mixed ethnicity and uptake, and large uncertainty in estimates for ‘Asian,’ ‘Other White’ or ‘Other Ethnicity’ communities.</li>
<li>Deprivation score was negatively associated with uptake, where as areas became more deprived uptake was lower.</li>
<li>The effect for population density looks misleading in the cleaned table due to rounding issues, but if we scroll back up to the messier table we can see that as population density increases (i.e., larger more populated urban areas) uptake falls</li>
</ul>
<p>A few questions for you to think about: Was this the correct statistical model? Were the correct explanatory variables used and what happens if you try others? Does the same associations persist if we look at second dose uptake?</p>
<p>One of the classical assumptions of an OLS regression model is the independence of errors (and to some extent observations as well). Since we have spatial data and areas closer together may be similar than those further apart (i.e., the characteristics and populations of Liverpool and Wirral are more similar than say, Liverpool and Guildford), this assumption may not hold. We can assess if this may be an issue through plotting the residuals (i.e., our error term <span class="math inline">\(\epsilon\)</span>) from the regression model and exploring if any spatial patterns exist.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="spatreg.html#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Join on </span></span>
<span id="cb70-2"><a href="spatreg.html#cb70-2" aria-hidden="true" tabindex="-1"></a>lad_eng <span class="ot">&lt;-</span> <span class="fu">cbind</span>(lad_eng, model1<span class="sc">$</span>residuals)</span>
<span id="cb70-3"><a href="spatreg.html#cb70-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-4"><a href="spatreg.html#cb70-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb70-5"><a href="spatreg.html#cb70-5" aria-hidden="true" tabindex="-1"></a>map2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="co"># Call ggplot command</span></span>
<span id="cb70-6"><a href="spatreg.html#cb70-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> lad_eng, <span class="fu">aes</span>(<span class="at">fill =</span> model1.residuals), <span class="at">lwd =</span> <span class="dv">0</span>) <span class="sc">+</span> <span class="co"># Define what to plot</span></span>
<span id="cb70-7"><a href="spatreg.html#cb70-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis</span>() <span class="sc">+</span> <span class="co"># Make colourblind friendly</span></span>
<span id="cb70-8"><a href="spatreg.html#cb70-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Longitude&quot;</span>) <span class="sc">+</span> <span class="co"># Add x-axis label</span></span>
<span id="cb70-9"><a href="spatreg.html#cb70-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Latitude&quot;</span>) <span class="sc">+</span> <span class="co"># Add y-axis label</span></span>
<span id="cb70-10"><a href="spatreg.html#cb70-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;First dose uptake model&quot;</span>, <span class="co"># Edit plot title</span></span>
<span id="cb70-11"><a href="spatreg.html#cb70-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">&quot;Residuals&quot;</span>) <span class="co"># Edit legend title</span></span>
<span id="cb70-12"><a href="spatreg.html#cb70-12" aria-hidden="true" tabindex="-1"></a>map2 <span class="co"># Print plot</span></span></code></pre></div>
<p><img src="Spatial-Data_files/figure-html/unnamed-chunk-44-1.png" width="672" /></p>
<p>If there were no issues here, we might expect to find a random pattern. However, we can see this isn’t always the case. A positive residual would suggest that the observed value of an area is greater than what the model would predict based on the coefficients and it’s local values for each explanatory variable. There are some clustering of values in the North West, London and other urban areas. Similarly, a negative value suggests lower observed uptake than we might expect/predict from the model. We can see evidence of this in the West and South East of England.</p>
<p>Our analysis may therefore benefit from having a spatial regression model.</p>
</div>
<div id="selecting-the-right-spatial-model" class="section level2" number="3.3">
<h2><span class="header-section-number">3.3</span> Selecting the right spatial model</h2>
<p>The first thing we might want to check is the extent that there is spatial clustering of our data. We will start here by checking this for our outcome variable and the regression model residuals. We will follow the same methods that we introduced in the <a href="cluster.html#cluster">previous session</a>.</p>
<p>We will need to identify the spatial structure of our dataset. We will follow the same previous method of assigning neighbouring areas based on Queen’s contiguity. One issue here is that we have two Local Authorities that are islands (Isles of Scilly and Isle of Wight) which do not have any neighbours. To solve this, we could either assign the two islands manually to their nearest ‘neighbour’ (e.g., Isles of Scilly to Cornwall) or remove them from our analysis. For the basis of teaching you the methods here <del>and because I am too lazy to code it up as it is a faff</del>, we will just remove them from the data. We ought to re-run our regression model since we are dropping two observations, but we will not to save time here (we will correct this later so stay tuned).</p>
<p>Let’s check the spatial clustering in our outcome variable through calculating the Moran’s I.</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="spatreg.html#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spdep) <span class="co"># Load package</span></span>
<span id="cb71-2"><a href="spatreg.html#cb71-2" aria-hidden="true" tabindex="-1"></a>lad_eng <span class="ot">&lt;-</span> lad_eng[lad_eng<span class="sc">$</span>lad19cd <span class="sc">!=</span> <span class="st">&quot;E06000053&quot;</span> <span class="sc">&amp;</span> lad_eng<span class="sc">$</span>lad19cd <span class="sc">!=</span> <span class="st">&quot;E06000046&quot;</span>,] <span class="co"># Drop Isles of Scilly or Isle of Wight</span></span>
<span id="cb71-3"><a href="spatreg.html#cb71-3" aria-hidden="true" tabindex="-1"></a>nb <span class="ot">&lt;-</span> <span class="fu">poly2nb</span>(lad_eng, <span class="at">queen =</span> <span class="cn">TRUE</span>) <span class="co"># Calculate queen contiguity for areas (slow)</span></span>
<span id="cb71-4"><a href="spatreg.html#cb71-4" aria-hidden="true" tabindex="-1"></a>lw <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(nb, <span class="at">style =</span> <span class="st">&quot;W&quot;</span>, <span class="at">zero.policy =</span> <span class="cn">TRUE</span>) <span class="co"># Assign weights based on list of neighbours</span></span>
<span id="cb71-5"><a href="spatreg.html#cb71-5" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">moran.test</span>(lad_eng<span class="sc">$</span>percent_first_dose, lw) <span class="co"># Calculate Moran&#39;s I</span></span>
<span id="cb71-6"><a href="spatreg.html#cb71-6" aria-hidden="true" tabindex="-1"></a>m1 <span class="co"># Print result</span></span></code></pre></div>
<pre><code>## 
##  Moran I test under randomisation
## 
## data:  lad_eng$percent_first_dose  
## weights: lw    
## 
## Moran I statistic standard deviate = 11.055, p-value &lt; 2.2e-16
## alternative hypothesis: greater
## sample estimates:
## Moran I statistic       Expectation          Variance 
##       0.407962351      -0.003184713       0.001383250</code></pre>
<p>A Moran’s I value of 0.4079624 would indicate existence of moderate spatial clustering of first COVID-19 vaccination dose uptake.</p>
<p>Next, we will repeat the analysis for the regression model residuals. Remember this is more important in checking the model assumptions.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="spatreg.html#cb73-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">moran.test</span>(lad_eng<span class="sc">$</span>model1.residuals, lw) <span class="co"># Calculate Moran&#39;s I</span></span>
<span id="cb73-2"><a href="spatreg.html#cb73-2" aria-hidden="true" tabindex="-1"></a>m2 <span class="co"># Print result</span></span></code></pre></div>
<pre><code>## 
##  Moran I test under randomisation
## 
## data:  lad_eng$model1.residuals  
## weights: lw    
## 
## Moran I statistic standard deviate = 7.4067, p-value = 6.476e-14
## alternative hypothesis: greater
## sample estimates:
## Moran I statistic       Expectation          Variance 
##       0.271550385      -0.003184713       0.001375889</code></pre>
<p>Here, a value of 0.2715504 suggests weak clustering. While low, the result is statistically significant suggesting it is important variation that we need to take in account in how we approach our regression analysis.</p>
<p>Do you think that was a bit of a faff to code up? Well, you can do the whole thing in a single line of code thanks to <code>spdep</code>’s <code>lm.morantest</code> command. Indeed, it can allow us to update our regression model with the dropped observations quickly too. <del>OK I should I have said this earlier to not waste your time, but sorry not sorry as it is useful to show the manual process I hope.</del></p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="spatreg.html#cb75-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(percent_first_dose <span class="sc">~</span> median_age <span class="sc">+</span> Other_White <span class="sc">+</span> Mixed <span class="sc">+</span> Black <span class="sc">+</span> Asian <span class="sc">+</span> Other <span class="sc">+</span> mean_imd_score <span class="sc">+</span> pop_density, <span class="at">data =</span> lad_eng) <span class="co"># Re-run regression model</span></span>
<span id="cb75-2"><a href="spatreg.html#cb75-2" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">lm.morantest</span>(model1, lw) <span class="co"># Run Moran&#39;s I analysis of residuals</span></span>
<span id="cb75-3"><a href="spatreg.html#cb75-3" aria-hidden="true" tabindex="-1"></a>m3 <span class="co"># Print results</span></span></code></pre></div>
<pre><code>## 
##  Global Moran I for regression residuals
## 
## data:  
## model: lm(formula = percent_first_dose ~ median_age + Other_White + Mixed + Black + Asian + Other + mean_imd_score +
## pop_density, data = lad_eng)
## weights: lw
## 
## Moran I statistic standard deviate = 7.6783, p-value = 8.061e-15
## alternative hypothesis: greater
## sample estimates:
## Observed Moran I      Expectation         Variance 
##      0.271337873     -0.010969132      0.001351802</code></pre>
<p>Again we get a similar result.</p>
<p>So we have a problem. How might we address it? It might be that we have left out some unmeasured explanatory covariates that would account for the spatial variation. This might not always be possible. A different approach would be to account for the spatial structure of our underlying dataset. We could do this by adding in a categorical variable representing each area as a fixed effect in the regression model. You can try this by re-running the previous code and adding into the formula <code>lad19cd</code> - what are the issues this brings? We could also extend this model to be a multi-level regression model where the area identifier is specified as a random effect (check out R package <code>lme4</code> for more here). Neither of these models explicitly accounts for the spatial nature of the data (i.e., the regression model does not know the spatial structure of the data).</p>
<p>The other thing we could do is use a spatial regression model that explicitly accounts for the locations of each data point. Here we tell the regression model that the spatial structure of data points matters for their interpretation (i.e., data points closer to each other are more similar than those further apart). There are <em>a lot</em> of different types of spatial regression models. How might we select the correct model?</p>
<p>Selection of models may be based on which specification we think best describes our data. This is hard to decide! The other approach is that we can utilise model fit statistics to assess which spatial models may improve upon the OLS regression model we previously fit. We can do this using <code>spdep</code>’s <code>lm.LMtests</code> function. Here we test for different features of <strong>spatial dependence</strong> in our data/model. For review here, please consult the lecture slides for this practical <a href="">located here</a>. Tl;dr spatial dependence is where the spatial configuration (i.e., structure of locations) affects our outcome.</p>
<p>We will focus in this practical on spatial lag and spatial error models. The following code tests for whether a spatially lagged dependent variable or spatial error dependence can improve our model fit. We can test for more things using this code, but for now we stick with these four tests.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="spatreg.html#cb77-1" aria-hidden="true" tabindex="-1"></a>spat_dep_test <span class="ot">&lt;-</span> <span class="fu">lm.LMtests</span>(model1, lw, <span class="at">test=</span><span class="fu">c</span>(<span class="st">&quot;LMerr&quot;</span>, <span class="st">&quot;LMlag&quot;</span>, <span class="st">&quot;RLMerr&quot;</span>, <span class="st">&quot;RLMlag&quot;</span>)) <span class="co"># Test for spatial dependence</span></span>
<span id="cb77-2"><a href="spatreg.html#cb77-2" aria-hidden="true" tabindex="-1"></a>spat_dep_test</span></code></pre></div>
<pre><code>## 
##  Lagrange multiplier diagnostics for spatial dependence
## 
## data:  
## model: lm(formula = percent_first_dose ~ median_age + Other_White + Mixed + Black + Asian + Other + mean_imd_score +
## pop_density, data = lad_eng)
## weights: lw
## 
## LMerr = 52.31, df = 1, p-value = 4.738e-13
## 
## 
##  Lagrange multiplier diagnostics for spatial dependence
## 
## data:  
## model: lm(formula = percent_first_dose ~ median_age + Other_White + Mixed + Black + Asian + Other + mean_imd_score +
## pop_density, data = lad_eng)
## weights: lw
## 
## LMlag = 37.432, df = 1, p-value = 9.466e-10
## 
## 
##  Lagrange multiplier diagnostics for spatial dependence
## 
## data:  
## model: lm(formula = percent_first_dose ~ median_age + Other_White + Mixed + Black + Asian + Other + mean_imd_score +
## pop_density, data = lad_eng)
## weights: lw
## 
## RLMerr = 24.317, df = 1, p-value = 8.171e-07
## 
## 
##  Lagrange multiplier diagnostics for spatial dependence
## 
## data:  
## model: lm(formula = percent_first_dose ~ median_age + Other_White + Mixed + Black + Asian + Other + mean_imd_score +
## pop_density, data = lad_eng)
## weights: lw
## 
## RLMlag = 9.4386, df = 1, p-value = 0.002125</code></pre>
<p>If we consider all of the tests, we can see that for each test of spatial dependence that they are each statistically significant. This would suggest that each spatial model can benefit our analysis and model fit. If none were significant, then we would use the OLS regression results.</p>
</div>
<div id="spatial-lag-model" class="section level2" number="3.4">
<h2><span class="header-section-number">3.4</span> Spatial lag model</h2>
<p>The first types of spatial models we will consider are those which incorporate a <strong>spatial lag</strong>. These models use variables that are spatially lagged, which means that they calculate measures for each area that characterise (e.g., mean value) their surrounding neighbours. Spatial lags might correspond to the outcome variable or explanatory variables. A spatial lag suggests that the surrounding areas have an influence on the outcome of an area.</p>
<div id="slx-spatially-lagged-model" class="section level3" number="3.4.1">
<h3><span class="header-section-number">3.4.1</span> SLX spatially lagged model</h3>
<p>The first spatial regression model we will consider is the <strong>SLX spatial lag model</strong>. SLX here means Spatially Lagged X-variables. We define the model as:</p>
<p><span class="math display">\[
y = X \beta + WX \theta + \epsilon
\]</span></p>
<p>The equation is a simple extension of the OLS regression equation. Our outcome variable <span class="math inline">\(y\)</span> is a function of our explanatory variables <span class="math inline">\(X\)</span> and their <span class="math inline">\(\beta\)</span> coefficients, a spatial lag coefficient <span class="math inline">\(\theta\)</span> of the <span class="math inline">\(X\)</span> variables based on a spatial weight <span class="math inline">\(W\)</span> and the error term <span class="math inline">\(\epsilon\)</span>. The <span class="math inline">\(\beta\)</span> value represents the <em>direct effect</em> of an explanatory variable and the <span class="math inline">\(\theta\)</span> value represents the <em>indirect effect</em>. An indirect effect is synonymous with a <em>spillover effect</em> whereby changes in <span class="math inline">\(x\)</span> in an area have on it’s surrounding neighbours based on how <span class="math inline">\(W\)</span> is defined. The spatial lags are exogenous in definition.</p>
<p>To fit the model, we use the R package <code>spatialreg</code> which allows us to fit cross-sectional spatial regression models. We re-run the previous analysis of first dose uptake using this spatial model and tidy the output (please note that <code>gtsummary</code> does not handle spatial models well).</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="spatreg.html#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spatialreg) <span class="co"># Load package</span></span>
<span id="cb79-2"><a href="spatreg.html#cb79-2" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lmSLX</span>(percent_first_dose <span class="sc">~</span> median_age <span class="sc">+</span> Other_White <span class="sc">+</span> Mixed <span class="sc">+</span> Black <span class="sc">+</span> Asian <span class="sc">+</span> Other <span class="sc">+</span> mean_imd_score <span class="sc">+</span> pop_density, <span class="at">data =</span> lad_eng, lw) <span class="co"># Spatial lag model</span></span>
<span id="cb79-3"><a href="spatreg.html#cb79-3" aria-hidden="true" tabindex="-1"></a>tbl_model2 <span class="ot">&lt;-</span> <span class="fu">tbl_regression</span>(model2, <span class="at">label =</span> <span class="fu">list</span>(median_age <span class="sc">~</span> <span class="st">&quot;Median age&quot;</span>, Other_White <span class="sc">~</span> <span class="st">&quot;Other White (%)&quot;</span>, Mixed <span class="sc">~</span> <span class="st">&quot;Mixed (%)&quot;</span>, Black <span class="sc">~</span> <span class="st">&quot;Black (%)&quot;</span>, Asian <span class="sc">~</span> <span class="st">&quot;Asian (%)&quot;</span>, Other <span class="sc">~</span> <span class="st">&quot;Other Ethnicity (%)&quot;</span>, mean_imd_score <span class="sc">~</span> <span class="st">&quot;Deprivation score&quot;</span>, pop_density <span class="sc">~</span> <span class="st">&quot;Population density&quot;</span>, lag.median_age <span class="sc">~</span> <span class="st">&quot;Lag: Median age&quot;</span>, lag.Other_White <span class="sc">~</span> <span class="st">&quot;Lag: Other White (%)&quot;</span>, lag.Mixed <span class="sc">~</span> <span class="st">&quot;Lag: Mixed (%)&quot;</span>, lag.Black <span class="sc">~</span> <span class="st">&quot;Lag: Black (%)&quot;</span>, lag.Asian <span class="sc">~</span> <span class="st">&quot;Lag: Asian (%)&quot;</span>, lag.Other <span class="sc">~</span> <span class="st">&quot;Lag: Other Ethnicity (%)&quot;</span>, lag.mean_imd_score <span class="sc">~</span> <span class="st">&quot;Lag: Deprivation score&quot;</span>, lag.pop_density <span class="sc">~</span> <span class="st">&quot;Lag: Population density&quot;</span>)) <span class="co"># Tidy model output</span></span>
<span id="cb79-4"><a href="spatreg.html#cb79-4" aria-hidden="true" tabindex="-1"></a>tbl_model2 <span class="co"># Print</span></span></code></pre></div>
<div id="spertspcry" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#spertspcry .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#spertspcry .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#spertspcry .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#spertspcry .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#spertspcry .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#spertspcry .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#spertspcry .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#spertspcry .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#spertspcry .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#spertspcry .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#spertspcry .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#spertspcry .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#spertspcry .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#spertspcry .gt_from_md > :first-child {
  margin-top: 0;
}

#spertspcry .gt_from_md > :last-child {
  margin-bottom: 0;
}

#spertspcry .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#spertspcry .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#spertspcry .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#spertspcry .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#spertspcry .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#spertspcry .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#spertspcry .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#spertspcry .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#spertspcry .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#spertspcry .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#spertspcry .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#spertspcry .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#spertspcry .gt_left {
  text-align: left;
}

#spertspcry .gt_center {
  text-align: center;
}

#spertspcry .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#spertspcry .gt_font_normal {
  font-weight: normal;
}

#spertspcry .gt_font_bold {
  font-weight: bold;
}

#spertspcry .gt_font_italic {
  font-style: italic;
}

#spertspcry .gt_super {
  font-size: 65%;
}

#spertspcry .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 65%;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Beta</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>95% CI</strong><sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>p-value</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">Median age</td>
<td class="gt_row gt_center">0.90</td>
<td class="gt_row gt_center">0.81, 1.0</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">Other White (%)</td>
<td class="gt_row gt_center">-0.08</td>
<td class="gt_row gt_center">-0.19, 0.03</td>
<td class="gt_row gt_center">0.2</td></tr>
    <tr><td class="gt_row gt_left">Mixed (%)</td>
<td class="gt_row gt_center">0.31</td>
<td class="gt_row gt_center">-0.01, 0.62</td>
<td class="gt_row gt_center">0.055</td></tr>
    <tr><td class="gt_row gt_left">Black (%)</td>
<td class="gt_row gt_center">-0.17</td>
<td class="gt_row gt_center">-0.29, -0.06</td>
<td class="gt_row gt_center">0.003</td></tr>
    <tr><td class="gt_row gt_left">Asian (%)</td>
<td class="gt_row gt_center">0.02</td>
<td class="gt_row gt_center">-0.03, 0.07</td>
<td class="gt_row gt_center">0.4</td></tr>
    <tr><td class="gt_row gt_left">Other Ethnicity (%)</td>
<td class="gt_row gt_center">-0.01</td>
<td class="gt_row gt_center">-0.24, 0.23</td>
<td class="gt_row gt_center">>0.9</td></tr>
    <tr><td class="gt_row gt_left">Deprivation score</td>
<td class="gt_row gt_center">-0.10</td>
<td class="gt_row gt_center">-0.15, -0.04</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">Population density</td>
<td class="gt_row gt_center">0.00</td>
<td class="gt_row gt_center">0.00, 0.00</td>
<td class="gt_row gt_center">0.4</td></tr>
    <tr><td class="gt_row gt_left">Lag: Median age</td>
<td class="gt_row gt_center">-0.07</td>
<td class="gt_row gt_center">-0.22, 0.09</td>
<td class="gt_row gt_center">0.4</td></tr>
    <tr><td class="gt_row gt_left">Lag: Other White (%)</td>
<td class="gt_row gt_center">0.04</td>
<td class="gt_row gt_center">-0.16, 0.23</td>
<td class="gt_row gt_center">0.7</td></tr>
    <tr><td class="gt_row gt_left">Lag: Mixed (%)</td>
<td class="gt_row gt_center">0.48</td>
<td class="gt_row gt_center">-0.14, 1.1</td>
<td class="gt_row gt_center">0.13</td></tr>
    <tr><td class="gt_row gt_left">Lag: Black (%)</td>
<td class="gt_row gt_center">-0.22</td>
<td class="gt_row gt_center">-0.45, 0.00</td>
<td class="gt_row gt_center">0.052</td></tr>
    <tr><td class="gt_row gt_left">Lag: Asian (%)</td>
<td class="gt_row gt_center">0.04</td>
<td class="gt_row gt_center">-0.06, 0.13</td>
<td class="gt_row gt_center">0.4</td></tr>
    <tr><td class="gt_row gt_left">Lag: Other Ethnicity (%)</td>
<td class="gt_row gt_center">-0.19</td>
<td class="gt_row gt_center">-0.68, 0.29</td>
<td class="gt_row gt_center">0.4</td></tr>
    <tr><td class="gt_row gt_left">Lag: Deprivation score</td>
<td class="gt_row gt_center">-0.01</td>
<td class="gt_row gt_center">-0.09, 0.06</td>
<td class="gt_row gt_center">0.7</td></tr>
    <tr><td class="gt_row gt_left">Lag: Population density</td>
<td class="gt_row gt_center">0.00</td>
<td class="gt_row gt_center">0.00, 0.00</td>
<td class="gt_row gt_center">0.046</td></tr>
  </tbody>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="4">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>1</em>
          </sup>
           
          CI = Confidence Interval
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table>
</div>
<p>To interpret the model can be difficult. The <span class="math inline">\(\beta\)</span> coefficients are not exactly the same. Rather, to understand the marginal effect of our covariates, we need to estimate their total impacts (i.e., direct effect + indirect effect). To do this, we use the following piece of code.</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="spatreg.html#cb80-1" aria-hidden="true" tabindex="-1"></a>model2_imp <span class="ot">&lt;-</span> <span class="fu">impacts</span>(model2, <span class="at">listw =</span> lw) <span class="co"># Estimate direct, indirect and total effects of variables</span></span>
<span id="cb80-2"><a href="spatreg.html#cb80-2" aria-hidden="true" tabindex="-1"></a>model2_imp <span class="co"># Print</span></span></code></pre></div>
<pre><code>## Impact measures (SLX, estimable):
##                       Direct      Indirect         Total
## median_age      0.9009090557 -0.0696177362  0.8312913196
## Other_White    -0.0790245349  0.0358434195 -0.0431811154
## Mixed           0.3057806432  0.4837927431  0.7895733864
## Black          -0.1732816347 -0.2225162881 -0.3957979227
## Asian           0.0188294285  0.0374534457  0.0562828742
## Other          -0.0058036010 -0.1928748969 -0.1986784979
## mean_imd_score -0.0971854562 -0.0125373425 -0.1097227986
## pop_density     0.0001022996 -0.0004974955 -0.0003951959</code></pre>
<p>You will see here these are exactly the same as <span class="math inline">\(\beta\)</span> coefficients for this model, however this will not always be the case. What is useful here is that we can see the direct impact in an area, the indirect effects surrounding each and the total effect of each factor considering both together. The spatial lags here are mostly non-statistically significant, other than for population density. It suggests that they bring little to the model.</p>
<p>Standard errors and p-values for these statistics can be estimated through the following modified version of the code.</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="spatreg.html#cb82-1" aria-hidden="true" tabindex="-1"></a>model2_imp_se <span class="ot">&lt;-</span> <span class="fu">summary</span>(<span class="fu">impacts</span>(model2, lw), <span class="at">zstats =</span> <span class="cn">TRUE</span>) <span class="co"># Estimate</span></span>
<span id="cb82-2"><a href="spatreg.html#cb82-2" aria-hidden="true" tabindex="-1"></a>model2_imp_se <span class="co"># Print</span></span></code></pre></div>
<pre><code>## Impact measures (SLX, estimable, n-k):
##                       Direct      Indirect         Total
## median_age      0.9009090557 -0.0696177362  0.8312913196
## Other_White    -0.0790245349  0.0358434195 -0.0431811154
## Mixed           0.3057806432  0.4837927431  0.7895733864
## Black          -0.1732816347 -0.2225162881 -0.3957979227
## Asian           0.0188294285  0.0374534457  0.0562828742
## Other          -0.0058036010 -0.1928748969 -0.1986784979
## mean_imd_score -0.0971854562 -0.0125373425 -0.1097227986
## pop_density     0.0001022996 -0.0004974955 -0.0003951959
## ========================================================
## Standard errors:
##                      Direct     Indirect        Total
## median_age     0.0479267084 0.0788605699 0.0759959852
## Other_White    0.0554022011 0.1005400225 0.0903636892
## Mixed          0.1589370191 0.3165363389 0.3306975306
## Black          0.0588396940 0.1139981394 0.1050719658
## Asian          0.0236130613 0.0476175809 0.0435460352
## Other          0.1174828586 0.2470964358 0.2521944956
## mean_imd_score 0.0268712927 0.0388509279 0.0305507387
## pop_density    0.0001209284 0.0002482232 0.0002218059
## ========================================================
## Z-values:
##                     Direct   Indirect      Total
## median_age     18.79764092 -0.8827952 10.9386215
## Other_White    -1.42637898  0.3565090 -0.4778591
## Mixed           1.92391077  1.5283956  2.3875999
## Black          -2.94497851 -1.9519291 -3.7669222
## Asian           0.79741581  0.7865466  1.2924914
## Other          -0.04939956 -0.7805653 -0.7877987
## mean_imd_score -3.61670192 -0.3227038 -3.5914941
## pop_density     0.84595204 -2.0042263 -1.7817198
## 
## p-values:
##                Direct     Indirect Total     
## median_age     &lt; 2.22e-16 0.377347 &lt; 2.22e-16
## Other_White    0.15375898 0.721459 0.63275046
## Mixed          0.05436577 0.126414 0.01695879
## Black          0.00322977 0.050947 0.00016527
## Asian          0.42520958 0.431547 0.19618704
## Other          0.96060088 0.435058 0.43081446
## mean_imd_score 0.00029838 0.746920 0.00032879
## pop_density    0.39757950 0.045046 0.07479493</code></pre>
<p>We can also compare the results from the spatial model to our original OLS regression model</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="spatreg.html#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tbl_merge</span>(<span class="fu">list</span>(tbl_model1, tbl_model2)) <span class="co"># Combine both model outputs together</span></span></code></pre></div>
<div id="wbrozugdew" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#wbrozugdew .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#wbrozugdew .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#wbrozugdew .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#wbrozugdew .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#wbrozugdew .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wbrozugdew .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#wbrozugdew .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#wbrozugdew .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#wbrozugdew .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#wbrozugdew .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#wbrozugdew .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#wbrozugdew .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#wbrozugdew .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#wbrozugdew .gt_from_md > :first-child {
  margin-top: 0;
}

#wbrozugdew .gt_from_md > :last-child {
  margin-bottom: 0;
}

#wbrozugdew .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#wbrozugdew .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#wbrozugdew .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#wbrozugdew .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#wbrozugdew .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#wbrozugdew .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#wbrozugdew .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#wbrozugdew .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wbrozugdew .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#wbrozugdew .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#wbrozugdew .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#wbrozugdew .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#wbrozugdew .gt_left {
  text-align: left;
}

#wbrozugdew .gt_center {
  text-align: center;
}

#wbrozugdew .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#wbrozugdew .gt_font_normal {
  font-weight: normal;
}

#wbrozugdew .gt_font_bold {
  font-weight: bold;
}

#wbrozugdew .gt_font_italic {
  font-style: italic;
}

#wbrozugdew .gt_super {
  font-size: 65%;
}

#wbrozugdew .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 65%;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="2" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="3">
        <span class="gt_column_spanner"><strong>Table 1</strong></span>
      </th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="3">
        <span class="gt_column_spanner"><strong>Table 2</strong></span>
      </th>
    </tr>
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Beta</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>95% CI</strong><sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>p-value</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Beta</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>95% CI</strong><sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>p-value</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">Median age</td>
<td class="gt_row gt_center">0.81</td>
<td class="gt_row gt_center">0.73, 0.90</td>
<td class="gt_row gt_center"><0.001</td>
<td class="gt_row gt_center">0.90</td>
<td class="gt_row gt_center">0.81, 1.0</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">Other White (%)</td>
<td class="gt_row gt_center">-0.07</td>
<td class="gt_row gt_center">-0.16, 0.02</td>
<td class="gt_row gt_center">0.11</td>
<td class="gt_row gt_center">-0.08</td>
<td class="gt_row gt_center">-0.19, 0.03</td>
<td class="gt_row gt_center">0.2</td></tr>
    <tr><td class="gt_row gt_left">Mixed (%)</td>
<td class="gt_row gt_center">0.40</td>
<td class="gt_row gt_center">0.09, 0.71</td>
<td class="gt_row gt_center">0.012</td>
<td class="gt_row gt_center">0.31</td>
<td class="gt_row gt_center">-0.01, 0.62</td>
<td class="gt_row gt_center">0.055</td></tr>
    <tr><td class="gt_row gt_left">Black (%)</td>
<td class="gt_row gt_center">-0.25</td>
<td class="gt_row gt_center">-0.35, -0.15</td>
<td class="gt_row gt_center"><0.001</td>
<td class="gt_row gt_center">-0.17</td>
<td class="gt_row gt_center">-0.29, -0.06</td>
<td class="gt_row gt_center">0.003</td></tr>
    <tr><td class="gt_row gt_left">Asian (%)</td>
<td class="gt_row gt_center">0.02</td>
<td class="gt_row gt_center">-0.02, 0.06</td>
<td class="gt_row gt_center">0.4</td>
<td class="gt_row gt_center">0.02</td>
<td class="gt_row gt_center">-0.03, 0.07</td>
<td class="gt_row gt_center">0.4</td></tr>
    <tr><td class="gt_row gt_left">Other Ethnicity (%)</td>
<td class="gt_row gt_center">-0.14</td>
<td class="gt_row gt_center">-0.36, 0.08</td>
<td class="gt_row gt_center">0.2</td>
<td class="gt_row gt_center">-0.01</td>
<td class="gt_row gt_center">-0.24, 0.23</td>
<td class="gt_row gt_center">>0.9</td></tr>
    <tr><td class="gt_row gt_left">Deprivation score</td>
<td class="gt_row gt_center">-0.10</td>
<td class="gt_row gt_center">-0.14, -0.06</td>
<td class="gt_row gt_center"><0.001</td>
<td class="gt_row gt_center">-0.10</td>
<td class="gt_row gt_center">-0.15, -0.04</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">Population density</td>
<td class="gt_row gt_center">0.00</td>
<td class="gt_row gt_center">0.00, 0.00</td>
<td class="gt_row gt_center">0.015</td>
<td class="gt_row gt_center">0.00</td>
<td class="gt_row gt_center">0.00, 0.00</td>
<td class="gt_row gt_center">0.4</td></tr>
    <tr><td class="gt_row gt_left">Lag: Median age</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">-0.07</td>
<td class="gt_row gt_center">-0.22, 0.09</td>
<td class="gt_row gt_center">0.4</td></tr>
    <tr><td class="gt_row gt_left">Lag: Other White (%)</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0.04</td>
<td class="gt_row gt_center">-0.16, 0.23</td>
<td class="gt_row gt_center">0.7</td></tr>
    <tr><td class="gt_row gt_left">Lag: Mixed (%)</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0.48</td>
<td class="gt_row gt_center">-0.14, 1.1</td>
<td class="gt_row gt_center">0.13</td></tr>
    <tr><td class="gt_row gt_left">Lag: Black (%)</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">-0.22</td>
<td class="gt_row gt_center">-0.45, 0.00</td>
<td class="gt_row gt_center">0.052</td></tr>
    <tr><td class="gt_row gt_left">Lag: Asian (%)</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0.04</td>
<td class="gt_row gt_center">-0.06, 0.13</td>
<td class="gt_row gt_center">0.4</td></tr>
    <tr><td class="gt_row gt_left">Lag: Other Ethnicity (%)</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">-0.19</td>
<td class="gt_row gt_center">-0.68, 0.29</td>
<td class="gt_row gt_center">0.4</td></tr>
    <tr><td class="gt_row gt_left">Lag: Deprivation score</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">-0.01</td>
<td class="gt_row gt_center">-0.09, 0.06</td>
<td class="gt_row gt_center">0.7</td></tr>
    <tr><td class="gt_row gt_left">Lag: Population density</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0.00</td>
<td class="gt_row gt_center">0.00, 0.00</td>
<td class="gt_row gt_center">0.046</td></tr>
  </tbody>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="7">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>1</em>
          </sup>
           
          CI = Confidence Interval
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table>
</div>
<p>Not a lot has changed if we compare the direct effects of coefficients (many remain within their 95% confidence intervals), probably because the spatial lagged effects were not strong or identifiable. Population density has become non-statistically significant mind you, as has percentage of people who with mixed ethnicity.</p>
<p>We can also compare model fit to see if the spatial model improves on the original OLS regression model. For example, we can check this by quickly looking at the AIC model fit.</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="spatreg.html#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(model1) <span class="co"># OLS regression model</span></span></code></pre></div>
<pre><code>## [1] 1424.31</code></pre>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="spatreg.html#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(model2) <span class="co"># SLX spatial lag model</span></span></code></pre></div>
<pre><code>## [1] 1406.79</code></pre>
<p>The spatial lag model does improve model fit overall.</p>
</div>
<div id="sar-spatial-lag" class="section level3" number="3.4.2">
<h3><span class="header-section-number">3.4.2</span> SAR Spatial Lag</h3>
<p>The other spatial lag model that we can specify is the following:</p>
<p><span class="math display">\[
y = \rho Wy + X\beta + \epsilon
\]</span></p>
<p>SAR stands for Spatial AutoRegressive model. Here, we have the standard OLS regression equation <span class="math inline">\(X\beta + \epsilon\)</span>, however we also have included a spatial lag component <span class="math inline">\(\rho W\)</span> of our outcome variable <span class="math inline">\(y\)</span>. <span class="math inline">\(W\)</span> is once again our spatial weights matrix, with <span class="math inline">\(\rho\)</span> representing the correlation of the spatial lag of <span class="math inline">\(y\)</span> to <span class="math inline">\(y\)</span>.</p>
<p>Since the model contains <span class="math inline">\(y\)</span> at both sides of the equation, it violates the exogeneity assumption of the OLS regression model. We therefore need a different approach to estimate the equation.</p>
<p>Please note: <code>gtsummary</code> does not handle spatial models well, so we will have to <del>fudge it</del> persist a bit here. If you can fix it, send your answers on a postcard/carrier pigeon please. Remember, you can always get the raw output of a model by using <code>summary(model3)</code>.</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="spatreg.html#cb89-1" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lagsarlm</span>(percent_first_dose <span class="sc">~</span> median_age <span class="sc">+</span> Other_White <span class="sc">+</span> Mixed <span class="sc">+</span> Black <span class="sc">+</span> Asian <span class="sc">+</span> Other <span class="sc">+</span> mean_imd_score <span class="sc">+</span> pop_density, <span class="at">data =</span> lad_eng, lw) <span class="co"># Model</span></span>
<span id="cb89-2"><a href="spatreg.html#cb89-2" aria-hidden="true" tabindex="-1"></a>tbl_model3 <span class="ot">&lt;-</span> <span class="fu">tbl_regression</span>(model3) <span class="co"># Tidy model output</span></span>
<span id="cb89-3"><a href="spatreg.html#cb89-3" aria-hidden="true" tabindex="-1"></a>tbl_model3 <span class="co"># Print</span></span></code></pre></div>
<div id="uxoietalfs" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#uxoietalfs .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#uxoietalfs .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#uxoietalfs .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#uxoietalfs .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#uxoietalfs .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#uxoietalfs .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#uxoietalfs .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#uxoietalfs .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#uxoietalfs .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#uxoietalfs .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#uxoietalfs .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#uxoietalfs .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#uxoietalfs .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#uxoietalfs .gt_from_md > :first-child {
  margin-top: 0;
}

#uxoietalfs .gt_from_md > :last-child {
  margin-bottom: 0;
}

#uxoietalfs .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#uxoietalfs .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#uxoietalfs .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#uxoietalfs .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#uxoietalfs .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#uxoietalfs .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#uxoietalfs .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#uxoietalfs .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#uxoietalfs .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#uxoietalfs .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#uxoietalfs .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#uxoietalfs .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#uxoietalfs .gt_left {
  text-align: left;
}

#uxoietalfs .gt_center {
  text-align: center;
}

#uxoietalfs .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#uxoietalfs .gt_font_normal {
  font-weight: normal;
}

#uxoietalfs .gt_font_bold {
  font-weight: bold;
}

#uxoietalfs .gt_font_italic {
  font-style: italic;
}

#uxoietalfs .gt_super {
  font-size: 65%;
}

#uxoietalfs .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 65%;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Beta</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>95% CI</strong><sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>p-value</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">rho</td>
<td class="gt_row gt_center">0.23</td>
<td class="gt_row gt_center">0.16, 0.29</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">(Intercept)</td>
<td class="gt_row gt_center">16</td>
<td class="gt_row gt_center">10, 22</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">median_age</td>
<td class="gt_row gt_center">0.84</td>
<td class="gt_row gt_center">0.76, 0.92</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">Other_White</td>
<td class="gt_row gt_center">-0.09</td>
<td class="gt_row gt_center">-0.17, -0.01</td>
<td class="gt_row gt_center">0.029</td></tr>
    <tr><td class="gt_row gt_left">Mixed</td>
<td class="gt_row gt_center">0.39</td>
<td class="gt_row gt_center">0.10, 0.68</td>
<td class="gt_row gt_center">0.008</td></tr>
    <tr><td class="gt_row gt_left">Black</td>
<td class="gt_row gt_center">-0.17</td>
<td class="gt_row gt_center">-0.26, -0.07</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">Asian</td>
<td class="gt_row gt_center">0.04</td>
<td class="gt_row gt_center">0.00, 0.08</td>
<td class="gt_row gt_center">0.044</td></tr>
    <tr><td class="gt_row gt_left">Other</td>
<td class="gt_row gt_center">-0.04</td>
<td class="gt_row gt_center">-0.24, 0.16</td>
<td class="gt_row gt_center">0.7</td></tr>
    <tr><td class="gt_row gt_left">mean_imd_score</td>
<td class="gt_row gt_center">-0.11</td>
<td class="gt_row gt_center">-0.15, -0.08</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">pop_density</td>
<td class="gt_row gt_center">0.00</td>
<td class="gt_row gt_center">0.00, 0.00</td>
<td class="gt_row gt_center">0.15</td></tr>
  </tbody>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="4">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>1</em>
          </sup>
           
          CI = Confidence Interval
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table>
</div>
<p>Let’s compare it to our standard OLS regression model. We will go back to the untidy version of the output to match the above</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="spatreg.html#cb90-1" aria-hidden="true" tabindex="-1"></a>tbl_model1 <span class="ot">&lt;-</span> <span class="fu">tbl_regression</span>(model1, <span class="at">intercept =</span> <span class="cn">TRUE</span>) <span class="co"># Redo Table 1 to match above format</span></span>
<span id="cb90-2"><a href="spatreg.html#cb90-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tbl_merge</span>(<span class="at">tbls =</span> <span class="fu">list</span>(tbl_model1, tbl_model3), <span class="co"># Join output together</span></span>
<span id="cb90-3"><a href="spatreg.html#cb90-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">tab_spanner =</span> <span class="fu">c</span>(<span class="st">&quot;**OLS**&quot;</span>, <span class="st">&quot;**Spatial Lag**&quot;</span>)) <span class="co"># Rename columns (in bold)</span></span></code></pre></div>
<pre><code>## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead</code></pre>
<div id="oewslwquxi" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#oewslwquxi .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#oewslwquxi .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#oewslwquxi .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#oewslwquxi .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#oewslwquxi .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#oewslwquxi .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#oewslwquxi .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#oewslwquxi .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#oewslwquxi .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#oewslwquxi .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#oewslwquxi .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#oewslwquxi .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#oewslwquxi .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#oewslwquxi .gt_from_md > :first-child {
  margin-top: 0;
}

#oewslwquxi .gt_from_md > :last-child {
  margin-bottom: 0;
}

#oewslwquxi .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#oewslwquxi .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#oewslwquxi .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#oewslwquxi .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#oewslwquxi .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#oewslwquxi .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#oewslwquxi .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#oewslwquxi .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#oewslwquxi .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#oewslwquxi .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#oewslwquxi .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#oewslwquxi .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#oewslwquxi .gt_left {
  text-align: left;
}

#oewslwquxi .gt_center {
  text-align: center;
}

#oewslwquxi .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#oewslwquxi .gt_font_normal {
  font-weight: normal;
}

#oewslwquxi .gt_font_bold {
  font-weight: bold;
}

#oewslwquxi .gt_font_italic {
  font-style: italic;
}

#oewslwquxi .gt_super {
  font-size: 65%;
}

#oewslwquxi .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 65%;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="2" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="3">
        <span class="gt_column_spanner"><strong>OLS</strong></span>
      </th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="3">
        <span class="gt_column_spanner"><strong>Spatial Lag</strong></span>
      </th>
    </tr>
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Beta</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>95% CI</strong><sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>p-value</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Beta</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>95% CI</strong><sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>p-value</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">(Intercept)</td>
<td class="gt_row gt_center">32</td>
<td class="gt_row gt_center">28, 36</td>
<td class="gt_row gt_center"><0.001</td>
<td class="gt_row gt_center">16</td>
<td class="gt_row gt_center">10, 22</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">median_age</td>
<td class="gt_row gt_center">0.81</td>
<td class="gt_row gt_center">0.73, 0.90</td>
<td class="gt_row gt_center"><0.001</td>
<td class="gt_row gt_center">0.84</td>
<td class="gt_row gt_center">0.76, 0.92</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">Other_White</td>
<td class="gt_row gt_center">-0.07</td>
<td class="gt_row gt_center">-0.16, 0.02</td>
<td class="gt_row gt_center">0.13</td>
<td class="gt_row gt_center">-0.09</td>
<td class="gt_row gt_center">-0.17, -0.01</td>
<td class="gt_row gt_center">0.029</td></tr>
    <tr><td class="gt_row gt_left">Mixed</td>
<td class="gt_row gt_center">0.42</td>
<td class="gt_row gt_center">0.10, 0.73</td>
<td class="gt_row gt_center">0.009</td>
<td class="gt_row gt_center">0.39</td>
<td class="gt_row gt_center">0.10, 0.68</td>
<td class="gt_row gt_center">0.008</td></tr>
    <tr><td class="gt_row gt_left">Black</td>
<td class="gt_row gt_center">-0.25</td>
<td class="gt_row gt_center">-0.36, -0.15</td>
<td class="gt_row gt_center"><0.001</td>
<td class="gt_row gt_center">-0.17</td>
<td class="gt_row gt_center">-0.26, -0.07</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">Asian</td>
<td class="gt_row gt_center">0.02</td>
<td class="gt_row gt_center">-0.02, 0.06</td>
<td class="gt_row gt_center">0.4</td>
<td class="gt_row gt_center">0.04</td>
<td class="gt_row gt_center">0.00, 0.08</td>
<td class="gt_row gt_center">0.044</td></tr>
    <tr><td class="gt_row gt_left">Other</td>
<td class="gt_row gt_center">-0.14</td>
<td class="gt_row gt_center">-0.36, 0.07</td>
<td class="gt_row gt_center">0.2</td>
<td class="gt_row gt_center">-0.04</td>
<td class="gt_row gt_center">-0.24, 0.16</td>
<td class="gt_row gt_center">0.7</td></tr>
    <tr><td class="gt_row gt_left">mean_imd_score</td>
<td class="gt_row gt_center">-0.10</td>
<td class="gt_row gt_center">-0.14, -0.06</td>
<td class="gt_row gt_center"><0.001</td>
<td class="gt_row gt_center">-0.11</td>
<td class="gt_row gt_center">-0.15, -0.08</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">pop_density</td>
<td class="gt_row gt_center">0.00</td>
<td class="gt_row gt_center">0.00, 0.00</td>
<td class="gt_row gt_center">0.013</td>
<td class="gt_row gt_center">0.00</td>
<td class="gt_row gt_center">0.00, 0.00</td>
<td class="gt_row gt_center">0.15</td></tr>
    <tr><td class="gt_row gt_left">rho</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0.23</td>
<td class="gt_row gt_center">0.16, 0.29</td>
<td class="gt_row gt_center"><0.001</td></tr>
  </tbody>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="7">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>1</em>
          </sup>
           
          CI = Confidence Interval
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table>
</div>
<p>Not a lot has changed between the models, suggesting that the spatial patterns captured very little of the patterns observed in our covariates. The most interesting difference is for our population density variable <code>pop_density</code>, which has gone from statistically significant in our OLS regression model to insignificant in our spatial lag model. The percentage of people with their ethnicity as other White (<code>Other_White</code>) has now become statistically significant as well, with a negative association to the percentage vaccinated. Otherwise, the coefficients have remained similar and within the 95% Confidence Intervals of the OLS estimates.</p>
<p>The summary output for the spatial lag model gives us only the direct impacts for our coefficients, however we may be interested in the direct, indirect and total effects each covariate is having on our outcome variable.</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="spatreg.html#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">impacts</span>(model3, <span class="at">listw =</span> lw) <span class="co"># Estimate direct and indirect effects</span></span></code></pre></div>
<pre><code>## Impact measures (lag, exact):
##                       Direct      Indirect         Total
## median_age      0.8509693217  2.364693e-01  1.0874386629
## Other_White    -0.0930566879 -2.585881e-02 -0.1189154975
## Mixed           0.3929949698  1.092064e-01  0.5022013292
## Black          -0.1678335124 -4.663797e-02 -0.2144714806
## Asian           0.0406973608  1.130908e-02  0.0520064384
## Other          -0.0389923533 -1.083529e-02 -0.0498276394
## mean_imd_score -0.1152847834 -3.203560e-02 -0.1473203881
## pop_density    -0.0001353991 -3.762503e-05 -0.0001730242</code></pre>
<p>The table would suggest that the indirect effects of each covariate on the surrounding areas means that focusing on the direct association alone underestimates the total impact of each variable.</p>
<p>To get the standard errors and p-values for our direct, indirect and total effects, we use the following code. Unlike the SLX model, we cannot estimate these directly and therefore must use simulations (MCMC) approaches to estimate them. This only requires a slight modification to the code, in our case we will add in 500 simulations (the more the merrier, but impacts on processing time).</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="spatreg.html#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">impacts</span>(model3, <span class="at">listw =</span> lw, <span class="at">R =</span> <span class="dv">500</span>), <span class="at">zstats =</span> <span class="cn">TRUE</span>) <span class="co"># Slow, but gives quantiles etc</span></span></code></pre></div>
<pre><code>## Impact measures (lag, exact):
##                       Direct      Indirect         Total
## median_age      0.8509693217  2.364693e-01  1.0874386629
## Other_White    -0.0930566879 -2.585881e-02 -0.1189154975
## Mixed           0.3929949698  1.092064e-01  0.5022013292
## Black          -0.1678335124 -4.663797e-02 -0.2144714806
## Asian           0.0406973608  1.130908e-02  0.0520064384
## Other          -0.0389923533 -1.083529e-02 -0.0498276394
## mean_imd_score -0.1152847834 -3.203560e-02 -0.1473203881
## pop_density    -0.0001353991 -3.762503e-05 -0.0001730242
## ========================================================
## Simulation results (asymptotic variance matrix):
## Direct:
## 
## Iterations = 1:500
## Thinning interval = 1 
## Number of chains = 1 
## Sample size per chain = 500 
## 
## 1. Empirical mean and standard deviation for each variable,
##    plus standard error of the mean:
## 
##                      Mean        SD  Naive SE Time-series SE
## median_age      0.8525121 4.038e-02 1.806e-03      1.806e-03
## Other_White    -0.0931258 4.419e-02 1.976e-03      1.976e-03
## Mixed           0.3982622 1.494e-01 6.682e-03      6.682e-03
## Black          -0.1656767 5.150e-02 2.303e-03      2.157e-03
## Asian           0.0403707 2.028e-02 9.068e-04      9.068e-04
## Other          -0.0346247 1.024e-01 4.580e-03      4.580e-03
## mean_imd_score -0.1137616 1.920e-02 8.588e-04      8.588e-04
## pop_density    -0.0001375 9.734e-05 4.353e-06      4.353e-06
## 
## 2. Quantiles for each variable:
## 
##                      2.5%       25%        50%        75%      97.5%
## median_age      0.7742765  0.825442  0.8538912  8.782e-01  9.249e-01
## Other_White    -0.1786118 -0.121101 -0.0927149 -6.467e-02 -1.025e-02
## Mixed           0.1137999  0.303110  0.4026023  4.936e-01  6.791e-01
## Black          -0.2702979 -0.200784 -0.1657098 -1.294e-01 -7.291e-02
## Asian           0.0013119  0.025561  0.0400029  5.471e-02  7.826e-02
## Other          -0.2354788 -0.098935 -0.0333859  3.072e-02  1.562e-01
## mean_imd_score -0.1501918 -0.126077 -0.1143237 -1.021e-01 -7.450e-02
## pop_density    -0.0003154 -0.000204 -0.0001362 -7.563e-05  5.295e-05
## 
## ========================================================
## Indirect:
## 
## Iterations = 1:500
## Thinning interval = 1 
## Number of chains = 1 
## Sample size per chain = 500 
## 
## 1. Empirical mean and standard deviation for each variable,
##    plus standard error of the mean:
## 
##                      Mean        SD  Naive SE Time-series SE
## median_age      2.405e-01 5.020e-02 2.245e-03      2.245e-03
## Other_White    -2.644e-02 1.424e-02 6.370e-04      5.752e-04
## Mixed           1.129e-01 4.999e-02 2.235e-03      2.235e-03
## Black          -4.619e-02 1.592e-02 7.122e-04      7.122e-04
## Asian           1.156e-02 6.640e-03 2.969e-04      2.969e-04
## Other          -9.145e-03 2.925e-02 1.308e-03      1.308e-03
## mean_imd_score -3.218e-02 8.807e-03 3.939e-04      3.591e-04
## pop_density    -3.786e-05 2.731e-05 1.221e-06      1.221e-06
## 
## 2. Quantiles for each variable:
## 
##                      2.5%        25%        50%        75%      97.5%
## median_age      1.536e-01  2.041e-01  2.366e-01  2.754e-01  3.402e-01
## Other_White    -5.527e-02 -3.480e-02 -2.552e-02 -1.696e-02 -2.372e-03
## Mixed           2.852e-02  7.892e-02  1.091e-01  1.447e-01  2.175e-01
## Black          -7.968e-02 -5.651e-02 -4.486e-02 -3.477e-02 -1.970e-02
## Asian           3.712e-04  6.883e-03  1.076e-02  1.592e-02  2.528e-02
## Other          -7.010e-02 -2.694e-02 -9.219e-03  8.430e-03  4.732e-02
## mean_imd_score -5.121e-02 -3.791e-02 -3.172e-02 -2.601e-02 -1.645e-02
## pop_density    -9.482e-05 -5.543e-05 -3.776e-05 -2.012e-05  1.481e-05
## 
## ========================================================
## Total:
## 
## Iterations = 1:500
## Thinning interval = 1 
## Number of chains = 1 
## Sample size per chain = 500 
## 
## 1. Empirical mean and standard deviation for each variable,
##    plus standard error of the mean:
## 
##                      Mean        SD  Naive SE Time-series SE
## median_age      1.0929770 0.0736553 3.294e-03      3.294e-03
## Other_White    -0.1195685 0.0574824 2.571e-03      2.571e-03
## Mixed           0.5111369 0.1947910 8.711e-03      8.711e-03
## Black          -0.2118644 0.0650089 2.907e-03      2.907e-03
## Asian           0.0519308 0.0264846 1.184e-03      1.184e-03
## Other          -0.0437694 0.1311488 5.865e-03      5.865e-03
## mean_imd_score -0.1459417 0.0260142 1.163e-03      1.163e-03
## pop_density    -0.0001753 0.0001234 5.517e-06      5.517e-06
## 
## 2. Quantiles for each variable:
## 
##                      2.5%        25%        50%        75%      97.5%
## median_age      0.9555211  1.0432652  1.0900711  1.146e+00  1.236e+00
## Other_White    -0.2328298 -0.1560703 -0.1194452 -8.298e-02 -1.277e-02
## Mixed           0.1390956  0.3846310  0.5179249  6.328e-01  8.995e-01
## Black          -0.3357829 -0.2559570 -0.2117105 -1.670e-01 -9.434e-02
## Asian           0.0016831  0.0328099  0.0516210  7.085e-02  1.019e-01
## Other          -0.3009490 -0.1265225 -0.0430737  4.023e-02  1.966e-01
## mean_imd_score -0.1950171 -0.1623149 -0.1468028 -1.305e-01 -9.528e-02
## pop_density    -0.0003987 -0.0002676 -0.0001727 -9.592e-05  6.967e-05
## 
## ========================================================
## Simulated standard errors
##                      Direct     Indirect        Total
## median_age     4.038093e-02 5.020011e-02 0.0736552558
## Other_White    4.419156e-02 1.424436e-02 0.0574823745
## Mixed          1.494219e-01 4.998651e-02 0.1947909898
## Black          5.149804e-02 1.592425e-02 0.0650089053
## Asian          2.027763e-02 6.639541e-03 0.0264846444
## Other          1.024182e-01 2.925324e-02 0.1311488321
## mean_imd_score 1.920265e-02 8.807172e-03 0.0260142304
## pop_density    9.734392e-05 2.730753e-05 0.0001233592
## 
## Simulated z-values:
##                    Direct   Indirect     Total
## median_age     21.1117524  4.7901252 14.839090
## Other_White    -2.1073216 -1.8563599 -2.080090
## Mixed           2.6653536  2.2581031  2.624027
## Black          -3.2171469 -2.9004602 -3.259006
## Asian           1.9908999  1.7410899  1.960788
## Other          -0.3380712 -0.3126044 -0.333738
## mean_imd_score -5.9242663 -3.6538507 -5.610072
## pop_density    -1.4122687 -1.3864974 -1.421358
## 
## Simulated p-values:
##                Direct     Indirect   Total     
## median_age     &lt; 2.22e-16 1.6668e-06 &lt; 2.22e-16
## Other_White    0.0350897  0.06340228 0.0375173 
## Mixed          0.0076907  0.02393924 0.0086897 
## Black          0.0012947  0.00372615 0.0011180 
## Asian          0.0464919  0.08166783 0.0499038 
## Other          0.7353095  0.75458121 0.7385772 
## mean_imd_score 3.1369e-09 0.00025834 2.0224e-08
## pop_density    0.1578709  0.16559506 0.1552128</code></pre>
<p>It gives a lot of output, but it is useful to pick apart how useful our estimates are.</p>
</div>
</div>
<div id="spatial-error-models" class="section level2" number="3.5">
<h2><span class="header-section-number">3.5</span> Spatial error models</h2>
<p>We next explore how to implement spatial error models. The underlying models are modified OLS regression models meaning the models are more straightforward ways of accounting for spatial processes in our analysis, as well as being fairly easy to interpret. In this section, we will deal with models that incorporate the spatial structure of the dataset within the error terms. Remember that this was the key OLS assumption that might have been violated (i.e., independence of errors).</p>
<div id="spatial-error-model-sem" class="section level3" number="3.5.1">
<h3><span class="header-section-number">3.5.1</span> Spatial Error Model (SEM)</h3>
<p>The main equation that we are trying to estimate in our spatial error model is:</p>
<p><span class="math display">\[
y = X\beta + u
\]</span></p>
<p>Here, we are trying to explain our outcome variable <span class="math inline">\(y\)</span> based upon our the <span class="math inline">\(\beta\)</span> coefficients of covariate variables <span class="math inline">\(X\)</span> plus our error term <span class="math inline">\(u\)</span>. The equation itself looks fairly similar to the OLS equation, until we introduce the spatial autocorrelation element to our model. We partition <span class="math inline">\(u\)</span> into the following:</p>
<p><span class="math display">\[
u = \lambda Wu + \epsilon
\]</span></p>
<p>We define <span class="math inline">\(u\)</span> as a coefficient <span class="math inline">\(\lambda\)</span> controlling the spatial weight <span class="math inline">\(W\)</span> placed on the the error terms <span class="math inline">\(u\)</span>, plus the general error term <span class="math inline">\(\epsilon\)</span> for our model.</p>
<p>We cannot use the OLS regression model to estimate the equation, since the assumption of independence of error terms is violated. We therefore require new approaches to do this. Again, <code>gtsummary</code> doesn’t like these types of models but I have included here as it helps clean the output up.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="spatreg.html#cb96-1" aria-hidden="true" tabindex="-1"></a>model4 <span class="ot">&lt;-</span> <span class="fu">errorsarlm</span>(percent_first_dose <span class="sc">~</span> median_age <span class="sc">+</span> Other_White <span class="sc">+</span> Mixed <span class="sc">+</span> Black <span class="sc">+</span> Asian <span class="sc">+</span> Other <span class="sc">+</span> mean_imd_score <span class="sc">+</span> pop_density, <span class="at">data =</span> lad_eng, lw) <span class="co"># Model</span></span>
<span id="cb96-2"><a href="spatreg.html#cb96-2" aria-hidden="true" tabindex="-1"></a>tbl_model4 <span class="ot">&lt;-</span> <span class="fu">tbl_regression</span>(model4) <span class="co"># Tidy model output</span></span></code></pre></div>
<pre><code>## x Unable to identify the list of variables.
## 
## This is usually due to an error calling `stats::model.frame(x)`or `stats::model.matrix(x)`.
## It could be the case if that type of model does not implement these methods.
## Rarely, this error may occur if the model object was created within
## a functional programming framework (e.g. using `lappy()`, `purrr::map()`, etc.).</code></pre>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="spatreg.html#cb98-1" aria-hidden="true" tabindex="-1"></a>tbl_model4 <span class="co"># Print</span></span></code></pre></div>
<pre><code>## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead

## Warning: `columns = vars(...)` has been deprecated in gt 0.3.0:
## * please use `columns = c(...)` instead</code></pre>
<div id="sbgjgzhvtc" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#sbgjgzhvtc .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#sbgjgzhvtc .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#sbgjgzhvtc .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#sbgjgzhvtc .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#sbgjgzhvtc .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#sbgjgzhvtc .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#sbgjgzhvtc .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#sbgjgzhvtc .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#sbgjgzhvtc .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#sbgjgzhvtc .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#sbgjgzhvtc .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#sbgjgzhvtc .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#sbgjgzhvtc .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#sbgjgzhvtc .gt_from_md > :first-child {
  margin-top: 0;
}

#sbgjgzhvtc .gt_from_md > :last-child {
  margin-bottom: 0;
}

#sbgjgzhvtc .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#sbgjgzhvtc .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#sbgjgzhvtc .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#sbgjgzhvtc .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#sbgjgzhvtc .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#sbgjgzhvtc .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#sbgjgzhvtc .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#sbgjgzhvtc .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#sbgjgzhvtc .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#sbgjgzhvtc .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#sbgjgzhvtc .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#sbgjgzhvtc .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#sbgjgzhvtc .gt_left {
  text-align: left;
}

#sbgjgzhvtc .gt_center {
  text-align: center;
}

#sbgjgzhvtc .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#sbgjgzhvtc .gt_font_normal {
  font-weight: normal;
}

#sbgjgzhvtc .gt_font_bold {
  font-weight: bold;
}

#sbgjgzhvtc .gt_font_italic {
  font-style: italic;
}

#sbgjgzhvtc .gt_super {
  font-size: 65%;
}

#sbgjgzhvtc .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 65%;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Beta</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>95% CI</strong><sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>p-value</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">(Intercept)</td>
<td class="gt_row gt_center">29</td>
<td class="gt_row gt_center">25, 33</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">median_age</td>
<td class="gt_row gt_center">0.87</td>
<td class="gt_row gt_center">0.79, 0.95</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">Other_White</td>
<td class="gt_row gt_center">-0.11</td>
<td class="gt_row gt_center">-0.19, -0.02</td>
<td class="gt_row gt_center">0.020</td></tr>
    <tr><td class="gt_row gt_left">Mixed</td>
<td class="gt_row gt_center">0.24</td>
<td class="gt_row gt_center">-0.03, 0.51</td>
<td class="gt_row gt_center">0.078</td></tr>
    <tr><td class="gt_row gt_left">Black</td>
<td class="gt_row gt_center">-0.19</td>
<td class="gt_row gt_center">-0.28, -0.09</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">Asian</td>
<td class="gt_row gt_center">0.01</td>
<td class="gt_row gt_center">-0.03, 0.05</td>
<td class="gt_row gt_center">0.5</td></tr>
    <tr><td class="gt_row gt_left">Other</td>
<td class="gt_row gt_center">0.00</td>
<td class="gt_row gt_center">-0.20, 0.19</td>
<td class="gt_row gt_center">>0.9</td></tr>
    <tr><td class="gt_row gt_left">mean_imd_score</td>
<td class="gt_row gt_center">-0.08</td>
<td class="gt_row gt_center">-0.12, -0.04</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">pop_density</td>
<td class="gt_row gt_center">0.00</td>
<td class="gt_row gt_center">0.00, 0.00</td>
<td class="gt_row gt_center">0.6</td></tr>
    <tr><td class="gt_row gt_left">lambda</td>
<td class="gt_row gt_center">0.62</td>
<td class="gt_row gt_center">0.51, 0.72</td>
<td class="gt_row gt_center"><0.001</td></tr>
  </tbody>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="4">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>1</em>
          </sup>
           
          CI = Confidence Interval
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table>
</div>
<p>These models do not have direct and indirect effects since the spatial component only affects the error term.</p>
<p>We may also want to check whether a spatial error model was relevant here through running a <strong>Hausman Test</strong> which compares if the model improves upon the OLS model.</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="spatreg.html#cb100-1" aria-hidden="true" tabindex="-1"></a>HausmanTest <span class="ot">&lt;-</span> <span class="fu">Hausman.test</span>(model4) <span class="co"># Run test</span></span>
<span id="cb100-2"><a href="spatreg.html#cb100-2" aria-hidden="true" tabindex="-1"></a>HausmanTest <span class="co"># Print</span></span></code></pre></div>
<pre><code>## 
##  Spatial Hausman test (asymptotic)
## 
## data:  NULL
## Hausman test = 21.562, df = 9, p-value = 0.01038</code></pre>
<p>The test suggests that the spatial error improves the model (i.e., we want it to be statistically significant).</p>
<p>We can compare the model output to the OLS and spatial lag models too.</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="spatreg.html#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tbl_merge</span>(<span class="at">tbls =</span> <span class="fu">list</span>(tbl_model1, tbl_model3, tbl_model4), <span class="co"># Join three model outputs together</span></span>
<span id="cb102-2"><a href="spatreg.html#cb102-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">tab_spanner =</span> <span class="fu">c</span>(<span class="st">&quot;**OLS**&quot;</span>, <span class="st">&quot;**Spatial Lag**&quot;</span>, <span class="st">&quot;**Spatial Error**&quot;</span>)) <span class="co"># Rename columns (in bold)</span></span></code></pre></div>
<div id="nymtpmrsvs" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#nymtpmrsvs .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#nymtpmrsvs .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#nymtpmrsvs .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#nymtpmrsvs .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#nymtpmrsvs .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#nymtpmrsvs .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#nymtpmrsvs .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#nymtpmrsvs .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#nymtpmrsvs .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#nymtpmrsvs .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#nymtpmrsvs .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#nymtpmrsvs .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#nymtpmrsvs .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#nymtpmrsvs .gt_from_md > :first-child {
  margin-top: 0;
}

#nymtpmrsvs .gt_from_md > :last-child {
  margin-bottom: 0;
}

#nymtpmrsvs .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#nymtpmrsvs .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#nymtpmrsvs .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#nymtpmrsvs .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#nymtpmrsvs .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#nymtpmrsvs .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#nymtpmrsvs .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#nymtpmrsvs .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#nymtpmrsvs .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#nymtpmrsvs .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#nymtpmrsvs .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#nymtpmrsvs .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#nymtpmrsvs .gt_left {
  text-align: left;
}

#nymtpmrsvs .gt_center {
  text-align: center;
}

#nymtpmrsvs .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#nymtpmrsvs .gt_font_normal {
  font-weight: normal;
}

#nymtpmrsvs .gt_font_bold {
  font-weight: bold;
}

#nymtpmrsvs .gt_font_italic {
  font-style: italic;
}

#nymtpmrsvs .gt_super {
  font-size: 65%;
}

#nymtpmrsvs .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 65%;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="2" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="3">
        <span class="gt_column_spanner"><strong>OLS</strong></span>
      </th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="3">
        <span class="gt_column_spanner"><strong>Spatial Lag</strong></span>
      </th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="3">
        <span class="gt_column_spanner"><strong>Spatial Error</strong></span>
      </th>
    </tr>
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Beta</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>95% CI</strong><sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>p-value</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Beta</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>95% CI</strong><sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>p-value</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Beta</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>95% CI</strong><sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>p-value</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">(Intercept)</td>
<td class="gt_row gt_center">32</td>
<td class="gt_row gt_center">28, 36</td>
<td class="gt_row gt_center"><0.001</td>
<td class="gt_row gt_center">16</td>
<td class="gt_row gt_center">10, 22</td>
<td class="gt_row gt_center"><0.001</td>
<td class="gt_row gt_center">29</td>
<td class="gt_row gt_center">25, 33</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">median_age</td>
<td class="gt_row gt_center">0.81</td>
<td class="gt_row gt_center">0.73, 0.90</td>
<td class="gt_row gt_center"><0.001</td>
<td class="gt_row gt_center">0.84</td>
<td class="gt_row gt_center">0.76, 0.92</td>
<td class="gt_row gt_center"><0.001</td>
<td class="gt_row gt_center">0.87</td>
<td class="gt_row gt_center">0.79, 0.95</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">Other_White</td>
<td class="gt_row gt_center">-0.07</td>
<td class="gt_row gt_center">-0.16, 0.02</td>
<td class="gt_row gt_center">0.13</td>
<td class="gt_row gt_center">-0.09</td>
<td class="gt_row gt_center">-0.17, -0.01</td>
<td class="gt_row gt_center">0.029</td>
<td class="gt_row gt_center">-0.11</td>
<td class="gt_row gt_center">-0.19, -0.02</td>
<td class="gt_row gt_center">0.020</td></tr>
    <tr><td class="gt_row gt_left">Mixed</td>
<td class="gt_row gt_center">0.42</td>
<td class="gt_row gt_center">0.10, 0.73</td>
<td class="gt_row gt_center">0.009</td>
<td class="gt_row gt_center">0.39</td>
<td class="gt_row gt_center">0.10, 0.68</td>
<td class="gt_row gt_center">0.008</td>
<td class="gt_row gt_center">0.24</td>
<td class="gt_row gt_center">-0.03, 0.51</td>
<td class="gt_row gt_center">0.078</td></tr>
    <tr><td class="gt_row gt_left">Black</td>
<td class="gt_row gt_center">-0.25</td>
<td class="gt_row gt_center">-0.36, -0.15</td>
<td class="gt_row gt_center"><0.001</td>
<td class="gt_row gt_center">-0.17</td>
<td class="gt_row gt_center">-0.26, -0.07</td>
<td class="gt_row gt_center"><0.001</td>
<td class="gt_row gt_center">-0.19</td>
<td class="gt_row gt_center">-0.28, -0.09</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">Asian</td>
<td class="gt_row gt_center">0.02</td>
<td class="gt_row gt_center">-0.02, 0.06</td>
<td class="gt_row gt_center">0.4</td>
<td class="gt_row gt_center">0.04</td>
<td class="gt_row gt_center">0.00, 0.08</td>
<td class="gt_row gt_center">0.044</td>
<td class="gt_row gt_center">0.01</td>
<td class="gt_row gt_center">-0.03, 0.05</td>
<td class="gt_row gt_center">0.5</td></tr>
    <tr><td class="gt_row gt_left">Other</td>
<td class="gt_row gt_center">-0.14</td>
<td class="gt_row gt_center">-0.36, 0.07</td>
<td class="gt_row gt_center">0.2</td>
<td class="gt_row gt_center">-0.04</td>
<td class="gt_row gt_center">-0.24, 0.16</td>
<td class="gt_row gt_center">0.7</td>
<td class="gt_row gt_center">0.00</td>
<td class="gt_row gt_center">-0.20, 0.19</td>
<td class="gt_row gt_center">>0.9</td></tr>
    <tr><td class="gt_row gt_left">mean_imd_score</td>
<td class="gt_row gt_center">-0.10</td>
<td class="gt_row gt_center">-0.14, -0.06</td>
<td class="gt_row gt_center"><0.001</td>
<td class="gt_row gt_center">-0.11</td>
<td class="gt_row gt_center">-0.15, -0.08</td>
<td class="gt_row gt_center"><0.001</td>
<td class="gt_row gt_center">-0.08</td>
<td class="gt_row gt_center">-0.12, -0.04</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">pop_density</td>
<td class="gt_row gt_center">0.00</td>
<td class="gt_row gt_center">0.00, 0.00</td>
<td class="gt_row gt_center">0.013</td>
<td class="gt_row gt_center">0.00</td>
<td class="gt_row gt_center">0.00, 0.00</td>
<td class="gt_row gt_center">0.15</td>
<td class="gt_row gt_center">0.00</td>
<td class="gt_row gt_center">0.00, 0.00</td>
<td class="gt_row gt_center">0.6</td></tr>
    <tr><td class="gt_row gt_left">rho</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0.23</td>
<td class="gt_row gt_center">0.16, 0.29</td>
<td class="gt_row gt_center"><0.001</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left">lambda</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0.62</td>
<td class="gt_row gt_center">0.51, 0.72</td>
<td class="gt_row gt_center"><0.001</td></tr>
  </tbody>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="10">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>1</em>
          </sup>
           
          CI = Confidence Interval
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table>
</div>
<p>The spatial error model looks relatively similar to the spatial lag model, although there are some differences with <code>Mixed</code> and <code>Asian</code> variables now being statistically insignificant.</p>
</div>
<div id="spatial-durbin-error" class="section level3" number="3.5.2">
<h3><span class="header-section-number">3.5.2</span> Spatial Durbin Error</h3>
<p>We can extend the spatial error model through adding in spatial lags for our x-variables, accounting for the spatial effects of independent variables. This requires only a minor modification of the spatial error model equation:</p>
<p><span class="math display">\[
y = X\beta + WX\theta + u
\]</span>
The key difference to the spatial error model is the introduction of <span class="math inline">\(WX\theta\)</span> which applies the spatial weight <span class="math inline">\(W\)</span> to the independent variables <span class="math inline">\(X\)</span> and our spatial autocorrelation coefficient <span class="math inline">\(\theta\)</span>.</p>
<p><span class="math inline">\(u\)</span> again is defined as:</p>
<p><span class="math display">\[
u = \lambda Wu + \epsilon
\]</span></p>
<p>We can fit this model using a slight change to the spatial error code. Please note that <code>gtsummary</code> does not like this type of model output either, so it is a little messy again.</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="spatreg.html#cb103-1" aria-hidden="true" tabindex="-1"></a>model5 <span class="ot">&lt;-</span> <span class="fu">errorsarlm</span>(percent_first_dose <span class="sc">~</span> median_age <span class="sc">+</span> Other_White <span class="sc">+</span> Mixed <span class="sc">+</span> Black <span class="sc">+</span> Asian <span class="sc">+</span> Other <span class="sc">+</span> mean_imd_score <span class="sc">+</span> pop_density, <span class="at">data =</span> lad_eng, lw, <span class="at">etype =</span> <span class="st">&quot;emixed&quot;</span>) <span class="co"># Fit model</span></span>
<span id="cb103-2"><a href="spatreg.html#cb103-2" aria-hidden="true" tabindex="-1"></a>tbl_model5 <span class="ot">&lt;-</span> <span class="fu">tbl_regression</span>(model5) <span class="co"># Tidy model output</span></span>
<span id="cb103-3"><a href="spatreg.html#cb103-3" aria-hidden="true" tabindex="-1"></a>tbl_model5 <span class="co"># Print</span></span></code></pre></div>
<div id="xrniunwets" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#xrniunwets .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#xrniunwets .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#xrniunwets .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#xrniunwets .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#xrniunwets .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xrniunwets .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#xrniunwets .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#xrniunwets .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#xrniunwets .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#xrniunwets .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#xrniunwets .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#xrniunwets .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#xrniunwets .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#xrniunwets .gt_from_md > :first-child {
  margin-top: 0;
}

#xrniunwets .gt_from_md > :last-child {
  margin-bottom: 0;
}

#xrniunwets .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#xrniunwets .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#xrniunwets .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#xrniunwets .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#xrniunwets .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#xrniunwets .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#xrniunwets .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#xrniunwets .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xrniunwets .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#xrniunwets .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#xrniunwets .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#xrniunwets .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#xrniunwets .gt_left {
  text-align: left;
}

#xrniunwets .gt_center {
  text-align: center;
}

#xrniunwets .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#xrniunwets .gt_font_normal {
  font-weight: normal;
}

#xrniunwets .gt_font_bold {
  font-weight: bold;
}

#xrniunwets .gt_font_italic {
  font-style: italic;
}

#xrniunwets .gt_super {
  font-size: 65%;
}

#xrniunwets .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 65%;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Beta</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>95% CI</strong><sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>p-value</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">(Intercept)</td>
<td class="gt_row gt_center">31</td>
<td class="gt_row gt_center">22, 41</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">median_age</td>
<td class="gt_row gt_center">0.91</td>
<td class="gt_row gt_center">0.83, 1.0</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">Other_White</td>
<td class="gt_row gt_center">-0.10</td>
<td class="gt_row gt_center">-0.19, -0.01</td>
<td class="gt_row gt_center">0.034</td></tr>
    <tr><td class="gt_row gt_left">Mixed</td>
<td class="gt_row gt_center">0.28</td>
<td class="gt_row gt_center">0.00, 0.57</td>
<td class="gt_row gt_center">0.049</td></tr>
    <tr><td class="gt_row gt_left">Black</td>
<td class="gt_row gt_center">-0.20</td>
<td class="gt_row gt_center">-0.30, -0.10</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">Asian</td>
<td class="gt_row gt_center">0.02</td>
<td class="gt_row gt_center">-0.02, 0.06</td>
<td class="gt_row gt_center">0.4</td></tr>
    <tr><td class="gt_row gt_left">Other</td>
<td class="gt_row gt_center">0.00</td>
<td class="gt_row gt_center">-0.20, 0.21</td>
<td class="gt_row gt_center">>0.9</td></tr>
    <tr><td class="gt_row gt_left">mean_imd_score</td>
<td class="gt_row gt_center">-0.07</td>
<td class="gt_row gt_center">-0.11, -0.03</td>
<td class="gt_row gt_center">0.001</td></tr>
    <tr><td class="gt_row gt_left">pop_density</td>
<td class="gt_row gt_center">0.00</td>
<td class="gt_row gt_center">0.00, 0.00</td>
<td class="gt_row gt_center">0.6</td></tr>
    <tr><td class="gt_row gt_left">lag.median_age</td>
<td class="gt_row gt_center">-0.08</td>
<td class="gt_row gt_center">-0.25, 0.08</td>
<td class="gt_row gt_center">0.3</td></tr>
    <tr><td class="gt_row gt_left">lag.Other_White</td>
<td class="gt_row gt_center">0.08</td>
<td class="gt_row gt_center">-0.14, 0.29</td>
<td class="gt_row gt_center">0.5</td></tr>
    <tr><td class="gt_row gt_left">lag.Mixed</td>
<td class="gt_row gt_center">0.62</td>
<td class="gt_row gt_center">-0.04, 1.3</td>
<td class="gt_row gt_center">0.064</td></tr>
    <tr><td class="gt_row gt_left">lag.Black</td>
<td class="gt_row gt_center">-0.11</td>
<td class="gt_row gt_center">-0.35, 0.14</td>
<td class="gt_row gt_center">0.4</td></tr>
    <tr><td class="gt_row gt_left">lag.Asian</td>
<td class="gt_row gt_center">0.02</td>
<td class="gt_row gt_center">-0.08, 0.12</td>
<td class="gt_row gt_center">0.7</td></tr>
    <tr><td class="gt_row gt_left">lag.Other</td>
<td class="gt_row gt_center">-0.38</td>
<td class="gt_row gt_center">-0.93, 0.16</td>
<td class="gt_row gt_center">0.2</td></tr>
    <tr><td class="gt_row gt_left">lag.mean_imd_score</td>
<td class="gt_row gt_center">-0.06</td>
<td class="gt_row gt_center">-0.14, 0.02</td>
<td class="gt_row gt_center">0.14</td></tr>
    <tr><td class="gt_row gt_left">lag.pop_density</td>
<td class="gt_row gt_center">0.00</td>
<td class="gt_row gt_center">0.00, 0.00</td>
<td class="gt_row gt_center">0.15</td></tr>
    <tr><td class="gt_row gt_left">lambda</td>
<td class="gt_row gt_center">0.55</td>
<td class="gt_row gt_center">0.43, 0.66</td>
<td class="gt_row gt_center"><0.001</td></tr>
  </tbody>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="4">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>1</em>
          </sup>
           
          CI = Confidence Interval
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table>
</div>
<p>The inclusion of spatial lags does not seem to bring much advantage here. Since we have introduced spatial lags into our model, we can also calculate the direct, indirect and total effects of covariates too. I have included the code for calculating standard errors, however we don’t need to run it again <del>because I am lazy</del>.</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="spatreg.html#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="fu">impacts</span>(model5, <span class="at">listw =</span> lw) <span class="co"># Calculate indirect, direct and total effects</span></span></code></pre></div>
<pre><code>## Impact measures (SDEM, estimable):
##                       Direct      Indirect         Total
## median_age      9.115621e-01 -0.0841690665  0.8273930013
## Other_White    -9.924527e-02  0.0753496736 -0.0238955924
## Mixed           2.834532e-01  0.6242855916  0.9077388144
## Black          -2.041149e-01 -0.1070505848 -0.3111654388
## Asian           1.583933e-02  0.0209621790  0.0368015073
## Other           3.784383e-03 -0.3849049537 -0.3811205710
## mean_imd_score -7.049241e-02 -0.0594952812 -0.1299876895
## pop_density     5.783698e-05 -0.0003724632 -0.0003146262</code></pre>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="spatreg.html#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="co"># summary(impacts(model3, listw = lw, R = 500), zstats = TRUE) # Slow, but gives quantiles, standard errors and p-values</span></span></code></pre></div>
<p>There are more extensions of these models <del>than you can shake a stick at</del> we could explore here - for example, SARAR or SARMA - and most of them are essentially different combinations of spatial lags and spatial error models. We can save them for a rainy day.</p>
</div>
</div>
<div id="summary-2" class="section level2" number="3.6">
<h2><span class="header-section-number">3.6</span> Summary</h2>
<p>In this practical session, we have explored how to extend the standard OLS regression model to incorporate spatial processes. We will continue this theme in the next, and final, session where we examine Geographically Weighted Regression.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="cluster.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="gwr.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Spatial Data.pdf", "Spatial Data.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
